// Generated by tools/build-cache.mjs. Do not edit by hand.
const CACHE = "ashen-company-bbf4cdb0d59762d3";
const ASSETS = [
  "./",
  "./index.html",
  "./src/style.css",
  "./src/campaign.css",
  "./src/battle.css",
  "./src/campaign-ui.js",
  "./src/battle-view.js",
  "./src/app.js",
  "./src/engine.js",
  "./src/map.js",
  "./src/portraits.js",
  "./manifest.webmanifest",
  "./assets/icon.svg",
  "./assets/battle/dirt-road.png",
  "./assets/battle/earth-01.png",
  "./assets/battle/grass-01.png",
  "./assets/battle/grass-02.png",
  "./assets/icon-192.png",
  "./assets/icon-512.png",
  "./assets/items/arming-sword.png",
  "./assets/items/brigandine.png",
  "./assets/items/buckler.png",
  "./assets/items/cloth-hood.png",
  "./assets/items/greathelm.png",
  "./assets/items/hunting-bow.png",
  "./assets/items/iron-helm.png",
  "./assets/items/kettle-helm.png",
  "./assets/items/kite-shield.png",
  "./assets/items/leather-cap.png",
  "./assets/items/leather-vest.png",
  "./assets/items/mail-shirt.png",
  "./assets/items/patched-coat.png",
  "./assets/items/plate-harness.png",
  "./assets/items/quilted-jack.png",
  "./assets/items/round-shield.png",
  "./assets/items/spear.png",
  "./assets/items/wood-axe.png",
  "./assets/portraits/armor-brigandine.png",
  "./assets/portraits/armor-leather.png",
  "./assets/portraits/armor-mail.png",
  "./assets/portraits/armor-padded.png",
  "./assets/portraits/armor-plate.png",
  "./assets/portraits/beard-black-01.png",
  "./assets/portraits/beard-brown-01.png",
  "./assets/portraits/body-03.png",
  "./assets/portraits/body-04.png",
  "./assets/portraits/hair-black-21.png",
  "./assets/portraits/hair-brown-21.png",
  "./assets/portraits/head-34.png",
  "./assets/portraits/helmet-greathelm.png",
  "./assets/portraits/helmet-hood.png",
  "./assets/portraits/helmet-kettle.png",
  "./assets/portraits/helmet-nasal.png",
  "./assets/portraits/shield-kite.png",
  "./assets/portraits/shield-round.png",
  "./assets/portraits/weapon-axe.png",
  "./assets/portraits/weapon-bow.png",
  "./assets/portraits/weapon-spear.png",
  "./assets/portraits/weapon-sword.png",
  "./assets/ui/asset_ammo_icon.png",
  "./assets/ui/asset_food_up.png",
  "./assets/ui/asset_medicine_icon.png",
  "./assets/ui/asset_money_small.png",
  "./assets/ui/asset_supplies_icon.png",
  "./assets/ui/background_inventory.png",
  "./assets/ui/camp_bg_01.jpg",
  "./assets/ui/dialog_background_01_wide.png",
  "./assets/ui/difficulty_legend.png",
  "./assets/ui/input_2_active.png",
  "./assets/ui/input_2_default.png",
  "./assets/ui/inventory_slot_helmet.png",
  "./assets/ui/mini_food_circle.png",
  "./assets/ui/papers_icon.png",
  "./assets/ui/popup_background_300x600.png",
  "./assets/world/banner_101.png",
  "./assets/world/banner_102.png",
  "./assets/world/banner_103.png",
  "./assets/world/city_01.png",
  "./assets/world/figure_player_assassin.png",
  "./assets/world/figure_player_beggar.png",
  "./assets/world/figure_player_berserker.png",
  "./assets/world/figure_player_crusader.png",
  "./assets/world/figure_player_druid.png",
  "./assets/world/figure_player_inquisition.png",
  "./assets/world/figure_player_legion.png",
  "./assets/world/figure_player_noble.png",
  "./assets/world/figure_player_nomad.png",
  "./assets/world/figure_player_party.png",
  "./assets/world/figure_player_ranger.png",
  "./assets/world/figure_player_seer.png",
  "./assets/world/figure_player_slave.png",
  "./assets/world/figure_player_trader.png",
  "./assets/world/figure_player_troupe.png",
  "./assets/world/figure_player_vala.png",
  "./assets/world/figure_player_warlock.png",
  "./assets/world/fortified_outpost_01.png",
  "./assets/world/harbor_sw.png",
  "./assets/world/houses_01_01.png",
  "./assets/world/houses_02_01.png",
  "./assets/world/houses_03_01.png",
  "./assets/world/legend_world_grass_hill_01.png",
  "./assets/world/legend_world_grass_hill_02.png",
  "./assets/world/legend_world_grass_hill_03.png",
  "./assets/world/stone_watchtower_01.png",
  "./assets/world/stronghold_01.png",
  "./assets/world/stronghold_02.png",
  "./assets/world/townhall_01.png",
  "./assets/world/townhall_02.png",
  "./assets/world/wheat_farm_01.png",
  "./assets/world/wheat_field_01.png",
  "./assets/world/winery_01.png",
  "./assets/world/world_detail_autumn_green_01.png",
  "./assets/world/world_detail_autumn_green_02.png",
  "./assets/world/world_detail_forest_green_01.png",
  "./assets/world/world_detail_forest_green_02.png",
  "./assets/world/world_detail_forest_green_03.png",
  "./assets/world/world_detail_forest_green_04.png",
  "./assets/world/world_forest_01.png",
  "./assets/world/world_forest_02.png",
  "./assets/world/world_grass_01.png",
  "./assets/world/world_grass_02.png",
  "./assets/world/world_grass_03.png",
  "./assets/world/world_grass_04.png",
  "./assets/world/world_highlands_01.png",
  "./assets/world/world_highlands_02.png",
  "./assets/world/world_highlands_03.png",
  "./assets/world/world_ocean_00.png",
  "./assets/world/world_plains_01.png",
  "./assets/world/world_plains_02.png",
  "./assets/world/world_plains_03.png",
  "./assets/world/world_snow_01.png",
  "./assets/world/world_snow_02.png",
  "./assets/world/world_swamp_01.png"
];
const urls = ASSETS.map(path => new URL(path, self.registration.scope).href);

self.addEventListener('install', event => event.waitUntil((async () => {
  const cache = await caches.open(CACHE);
  try {
    await cache.addAll(urls.map(url => new Request(url, { cache: 'reload' })));
    const present = await Promise.all(urls.map(url => cache.match(url)));
    if (!present.every(Boolean)) throw new Error('Offline cache is incomplete.');
    await self.skipWaiting();
  } catch (error) {
    await caches.delete(CACHE);
    throw error;
  }
})()));

self.addEventListener('activate', event => event.waitUntil((async () => {
  const cache = await caches.open(CACHE);
  const present = await Promise.all(urls.map(url => cache.match(url)));
  if (!present.every(Boolean)) throw new Error('Offline cache is incomplete.');
  const keys = await caches.keys();
  await Promise.all(keys.filter(key => key.startsWith('ashen-company-') && key !== CACHE).map(key => caches.delete(key)));
  await self.clients.claim();
})()));

self.addEventListener('fetch', event => {
  if (event.request.method !== 'GET' || !event.request.url.startsWith(self.registration.scope)) return;
  event.respondWith((async () => {
    const cache = await caches.open(CACHE);
    const cached = await cache.match(event.request, { ignoreSearch: true });
    if (cached) return cached;
    if (event.request.mode === 'navigate') {
      return await cache.match(new URL('./index.html', self.registration.scope).href) || Response.error();
    }
    return Response.error();
  })());
});

self.addEventListener('message', event => {
  if (event.data?.type !== 'CHECK_OFFLINE') return;
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    const present = await Promise.all(urls.map(url => cache.match(url)));
    event.ports[0]?.postMessage({
      ready: present.every(Boolean),
      count: present.filter(Boolean).length,
      expected: urls.length,
      cache: CACHE,
    });
  })());
});
