import test from 'node:test';
import assert from 'node:assert/strict';
import {createGame,startBattle} from '../src/engine.js';
import {battleHTML,tacticsHTML} from '../src/battle-view.js';
function battle(){const s=createGame(73);s.position={x:440,y:520};assert.equal(startBattle(s,'quarry-camp').ok,true);return s.battle;}
test('battle commands precede field navigation and both tactics controls describe the same selection',()=>{const b=battle();b.tactic='shield-wall';const html=battleHTML(b,0);assert.ok(html.indexOf('class="battle-controls"')<html.indexOf('class="battle-scroll"'));assert.ok(html.indexOf('data-battle-tactic')<html.indexOf('class="battle-scroll"'));assert.match(html,/data-tactic="shield-wall" aria-pressed="true"/);assert.match(html,/<option value="shield-wall" selected>Shield Wall/);assert.match(tacticsHTML('focus',true),/select data-battle-tactic aria-label="Company tactic" disabled/);});
test('battle counts show surviving combatants separately from allies and escaping units',()=>{const b=battle();b.units[0].alive=false;b.units[0].hp=0;b.units[1].escaped=true;b.units.push({...b.units[2],id:'ally-1',ally:true});b.units.find(u=>u.side==='enemy').escaped=true;assert.match(battleHTML(b,0),/1 brother · 2 enemies · 1 ally/);});
test('camera actions disable missing enemy/active targets but the company control remains available',()=>{const b=battle();for(const u of b.units.filter(u=>u.side==='enemy'))u.escaped=true;b.activeId=null;const html=battleHTML(b,0);assert.match(html,/data-battle-camera="enemy"[^>]*disabled/);assert.match(html,/data-battle-camera="active"[^>]*disabled/);assert.doesNotMatch(html,/data-battle-camera="company"[^>]*disabled/);});
test('active fighter shows actual health, AP and fatigue and logs/help remain expandable',()=>{const b=battle(),u=b.units[0];b.activeId=u.id;u.hp=62;u.ap=3;u.fatigue=17;const html=battleHTML(b,0);assert.ok(html.includes(`HP 62/${u.maxHp} · AP 3/9`));assert.ok(html.includes(`Fatigue 17/${u.maxFatigue}`));assert.match(html,/<details class="battle-log-details" open><summary>Combat log/);assert.match(html,/<details class="battle-morale-help"><summary>Morale effects/);b.rulesVersion=1;assert.match(battleHTML(b,0),/AP 3\/2/);});
