import test from 'node:test';
import assert from 'node:assert/strict';
import { createGame, getItem, getCompanyStats, getEquipment, equipItem, unequipItem, learnPerk, getPerkPoints, startBattle, advanceBattle, finishBattle, validateSave, getTownServiceQuote, useTownService, camp } from '../src/engine.js';
import { companySheetHTML } from '../src/campaign-ui.js';
import { portraitHTML } from '../src/portraits.js';

function add(s,id,condition=getItem(id).armor){s.inventory.push(id);s.inventoryCondition.push(condition);}
function layers(perks=[]){const s=createGame(73),p=s.party[0];p.level=4;p.perks=['layered-armor',...perks];add(s,'kraken-mantle');add(s,'scale-mantle');assert.equal(equipItem(s,p.id,'kraken-mantle').ok,true);assert.equal(equipItem(s,p.id,'scale-mantle','attachment-2').ok,true);return {s,p};}
function begin(s){s.position={x:440,y:520};assert.equal(startBattle(s,'quarry-camp').ok,true);return s.battle.units.find(u=>u.id==='captain');}

test('Layered Armor costs one normal perk point and unlocks at level four',()=>{const s=createGame(10),p=s.party[0];p.level=3;const old=structuredClone(s);assert.equal(learnPerk(s,p.id,'layered-armor').ok,false);assert.deepEqual(s,old);p.level=4;const points=getPerkPoints(p);assert.equal(learnPerk(s,p.id,'layered-armor').ok,true);assert.equal(getPerkPoints(p),points-1);assert.equal(learnPerk(s,p.id,'layered-armor').ok,false);assert.deepEqual(validateSave(s),s);});

test('Nimble and Fleet Footed ignore both attachments while actual fatigue still counts them',()=>{const {s,p}=layers(['nimble','fleet-footed']);p.equipment.armor='padded-gambeson';p.armorDurability.body=getItem('padded-gambeson').armor;p.equipment.helmet='leather-cap';p.armorDurability.head=getItem('leather-cap').armor;assert.ok(getItem('padded-gambeson').fatigue+getItem('leather-cap').fatigue<=15);const withoutNimble=getCompanyStats({...p,perks:p.perks.filter(x=>x!=='nimble')});const stats=getCompanyStats(p);assert.equal(stats.meleeDefense,withoutNimble.meleeDefense+5);const bare=getCompanyStats({...p,equipment:{...p.equipment,attachment:null,attachment2:null}});assert.equal(bare.maxFatigue-stats.maxFatigue,11);const u=begin(s);assert.equal(u.movementCredit,2);assert.deepEqual(validateSave(s),s);p.equipment.armor='mail-shirt';p.armorDurability.body=getItem('mail-shirt').armor;assert.equal(getCompanyStats(p).meleeDefense,getCompanyStats({...p,perks:p.perks.filter(x=>x!=='nimble')}).meleeDefense);});

test('Brawny and Relentless keep each attachment full stamina and initiative cost',()=>{const {p}=layers(['brawny','relentless']);const worn=getCompanyStats(p),bare=getCompanyStats({...p,equipment:{...p.equipment,attachment:null,attachment2:null}});assert.equal(bare.maxFatigue-worn.maxFatigue,11);assert.equal(bare.initiative-worn.initiative,11);});

test('second slot rejects absent perk, absent armor and non-attachments atomically',()=>{for(const mode of ['perk','armor','weapon']){const {s,p}=layers();assert.equal(unequipItem(s,p.id,'attachment2').ok,true);if(mode==='perk')p.perks=[];if(mode==='armor'){p.equipment.armor=null;p.equipment.attachment=null;p.armorDurability.body=0;p.armorDurability.attachment=0;}const id=mode==='weapon'?'arming-sword':'scale-mantle';if(mode==='weapon')add(s,id,null);const old=structuredClone(s);assert.equal(equipItem(s,p.id,id,'attachment-2').ok,false);assert.deepEqual(s,old);}});

test('two attachments swap independently and stow with body armor without losing condition',()=>{const {s,p}=layers();p.armorDurability.attachment=21;p.armorDurability.attachment2=13;add(s,'fur-mantle',9);assert.equal(equipItem(s,p.id,'fur-mantle','attachment-2').ok,true);assert.equal(p.armorDurability.attachment,21);assert.equal(p.armorDurability.attachment2,9);assert.equal(s.inventoryCondition[s.inventory.indexOf('scale-mantle')],13);while(s.inventory.length<510)add(s,'patched-coat');const old=structuredClone(s);assert.equal(unequipItem(s,p.id,'armor').ok,false);assert.deepEqual(s,old);s.inventory.pop();s.inventoryCondition.pop();assert.equal(unequipItem(s,p.id,'armor').ok,true);assert.equal(p.equipment.attachment2,null);assert.equal(s.inventoryCondition[s.inventory.indexOf('kraken-mantle')],21);assert.equal(s.inventoryCondition[s.inventory.indexOf('fur-mantle')],9);assert.deepEqual(validateSave(s),s);});

test('body damage exhausts outer slot two then slot one; head hits leave both fitted layers intact',()=>{let body,head;for(let seed=1;seed<=100&&(!body||!head);seed++){const {s,p}=layers();s.seed=seed;s.rng=seed;const u=begin(s),b=s.battle,a=b.units.find(x=>x.id==='enemy-1');Object.assign(u,{q:3,r:3,hp:300,maxHp:300,meleeDefense:-100,attachmentArmor:7,attachment2Armor:5});Object.assign(a,{q:4,r:3,meleeSkill:300});for(const x of b.units.filter(x=>x.side==='company'&&x!==u))Object.assign(x,{q:0,r:x.id==='scout'?0:1});b.turnIndex=b.turnOrder.indexOf(a.id);b.activeId=a.id;advanceBattle(s);const e=b.lastEvent;if(e.type==='attack'){if(e.head)head??={u,e};else body??={u,e};}}assert.ok(body&&head);assert.ok(body.e.armorDamage>12);assert.equal(body.u.attachment2Armor,0);assert.equal(body.u.attachmentArmor,0);assert.equal(body.u.bodyArmor,body.u.maxBodyArmor-(body.e.armorDamage-12));assert.equal(head.u.attachment2Armor,5);assert.equal(head.u.attachmentArmor,7);assert.equal(head.u.bodyArmor,head.u.maxBodyArmor);});

test('smithy and camp repair second attachment with its own durability',()=>{const {s,p}=layers();p.armorDurability.attachment=21;p.armorDurability.attachment2=13;s.position={x:350,y:460};const repairs=getTownServiceQuote(s,'smithy',p.id).entries[0].repairs;assert.equal(repairs.find(x=>x.slot==='attachment2').missing,67);s.gold=10000;assert.equal(useTownService(s,'smithy',p.id).ok,true);assert.equal(p.armorDurability.attachment2,80);assert.equal(p.armorDurability.attachment,90);p.armorDurability.attachment2=1;s.supplies.tools=1;for(const x of Object.values(s.bands))x.defeatedUntil=1000;assert.equal(camp(s).ok,true);assert.equal(p.armorDurability.attachment2,26);assert.equal(p.armorDurability.attachment,90);});

test('second attachment survives battle save and fallen recovery at its own remaining condition',()=>{const {s}=layers();const u=begin(s);u.attachmentArmor=21;u.attachment2Armor=13;assert.deepEqual(validateSave(s),s);u.hp=0;u.alive=false;for(const e of s.battle.units.filter(x=>x.side==='enemy')){e.hp=0;e.alive=false;}const survivor=s.battle.units.find(x=>x.side==='company'&&x.alive);s.battle.turnIndex=s.battle.turnOrder.indexOf(survivor.id);s.battle.activeId=survivor.id;advanceBattle(s);assert.equal(s.battle.status,'victory');assert.equal(finishBattle(s).ok,true);for(const [id,condition]of [['kraken-mantle',21],['scale-mantle',13]]){assert.equal(s.inventory.filter(x=>x===id).length,1);assert.equal(s.inventoryCondition[s.inventory.indexOf(id)],condition);}assert.deepEqual(validateSave(s),s);});

test('save validation rejects illegal second layers and migrates empty legacy slots',()=>{const {s,p}=layers();for(const kind of ['perk','armor','durability']){const bad=structuredClone(s);if(kind==='perk')bad.party[0].perks=[];if(kind==='armor')bad.party[0].equipment.armor=null;if(kind==='durability')bad.party[0].armorDurability.attachment2=81;assert.throws(()=>validateSave(bad));}begin(s);const bad=structuredClone(s);bad.battle.units.find(x=>x.id===p.id).maxAttachment2Armor=81;assert.throws(()=>validateSave(bad));const legacy=createGame(10);for(const person of legacy.party){delete person.equipment.attachment2;delete person.armorDurability.attachment2;}assert.ok(validateSave(legacy).party.every(x=>x.equipment.attachment2===null&&x.armorDurability.attachment2===0));});

test('company UI and portraits expose both fitted attachment layers and locked perk hint',()=>{const {s,p}=layers();const html=companySheetHTML(s,p,null,[]);assert.match(html,/data-item-location="attachment-2"/);assert.match(html,/Attachment 2/);const portrait=portraitHTML(p,getEquipment(p),150);assert.match(portrait,/data-layer="attachment2-front"/);assert.match(portrait,/data-layer="attachment-front"/);p.perks=[];p.equipment.attachment2=null;assert.match(companySheetHTML(s,p,null,[]),/Requires Layered Armor/);});
