import test from 'node:test';
import assert from 'node:assert/strict';
import {ITEMS,SETTLEMENTS,createGame,createFamedItemId,getItem,shieldMaximum,throwingCapacity,checkBlacksmithDiscovery,acceptBlacksmithQuest,turnInBlacksmithQuest,getLegendaryBlacksmith,getBlacksmithQuestEncounters,startBattle,resolveBattle,retreatBattle,finishBattle,validateSave,getReforgeQuote,reforgeItem,claimBlacksmithReward,equipItem,unequipItem,sellItem,buyItem} from '../src/engine.js';
import {extractForgeProfile,encodeForgeItem,FORGE_KEYS,encodeBoundedForgeItem} from '../src/reforged-items.js';
import {blacksmithPanelHTML,blacksmithJournalHTML} from '../src/blacksmith-ui.js';
const catalog=id=>ITEMS.find(x=>x.id===id);
const profile=item=>extractForgeProfile(item,catalog,{shieldMaximum});
const condition=id=>{const i=getItem(id);return i.slot==='shield'?shieldMaximum(id):i.throwing?throwingCapacity(i):i.armor??null;};
function stash(s,ids){s.inventory=[...ids];s.inventoryCondition=ids.map(condition);}
function discovered(seed=19){const s=createGame(seed);s.position={x:745,y:400};stash(s,Array.from({length:5},(_,i)=>createFamedItemId('arming-sword',i,3)));assert.equal(checkBlacksmithDiscovery(s),true);return s;}
function readyForge(seed=19){const s=discovered(seed);assert.equal(acceptBlacksmithQuest(s,1).ok,true);s.cargo={iron:8,timber:6};s.supplies.tools=10;assert.equal(turnInBlacksmithQuest(s,1).ok,true);for(let stage=2;stage<=4;stage++){assert.equal(acceptBlacksmithQuest(s,stage).ok,true);const site=getBlacksmithQuestEncounters(s)[0];s.position={x:site.x,y:site.y};assert.equal(startBattle(s,site.id).ok,true);assert.deepEqual(validateSave(s),s);s.battle.units.filter(u=>u.side==='enemy').forEach(u=>{u.hp=0;u.alive=false;});resolveBattle(s);assert.equal(finishBattle(s).ok,true);assert.equal(getLegendaryBlacksmith(s).quest.ready,true);s.position={x:745,y:400};assert.equal(turnInBlacksmithQuest(s,stage).ok,true);assert.deepEqual(validateSave(s),s);}assert.equal(getLegendaryBlacksmith(s).unlocked,true);s.cargo={iron:10,timber:10,wool:10};return s;}
function forge(s,donor,recipient,mode){const q=getReforgeQuote(s,donor,recipient,mode);assert.equal(q.ok,true,q.message);const r=reforgeItem(s,q);assert.equal(r.ok,true,r.message);assert.deepEqual(validateSave(s),s);return {q,r};}

test('daily discovery is latched, counts physical reserve copies and read-only UI does not change old saves',()=>{const s=createGame(4),old=structuredClone(s);getLegendaryBlacksmith(s);blacksmithPanelHTML(s);blacksmithJournalHTML(s);assert.deepEqual(s,old);assert.deepEqual(validateSave(s),old);assert.equal(checkBlacksmithDiscovery(s),false);stash(s,Array(5).fill(createFamedItemId('arming-sword',1)));assert.equal(checkBlacksmithDiscovery(s),false);s.day++;assert.equal(checkBlacksmithDiscovery(s),true);stash(s,[]);s.day++;assert.equal(checkBlacksmithDiscovery(s),false);assert.equal(getLegendaryBlacksmith(s).discovered,true);assert.deepEqual(validateSave(s),s);});
test('the complete independent quest chain unlocks the forge, one free operation, and a separately claimable one-time reward',()=>{const s=readyForge();const n=s.inventory.length;assert.equal(claimBlacksmithReward(s).ok,true);assert.equal(s.inventory.length,n+1);assert.equal(claimBlacksmithReward(s).ok,false);assert.deepEqual(validateSave(s),s);assert.match(blacksmithPanelHTML(s),/Sacrifice/);});
test('retreat retains survivors and wear for a saved retry',()=>{const s=discovered();acceptBlacksmithQuest(s,1);s.cargo={iron:8,timber:6};s.supplies.tools=10;turnInBlacksmithQuest(s,1);acceptBlacksmithQuest(s,2);const site=getBlacksmithQuestEncounters(s)[0];s.position={x:site.x,y:site.y};startBattle(s,site.id);const enemy=s.battle.units.find(u=>u.side==='enemy');enemy.hp-=5;enemy.bodyArmor=Math.max(0,enemy.bodyArmor-10);retreatBattle(s);finishBattle(s);assert.deepEqual(validateSave(s),s);const retry=getBlacksmithQuestEncounters(s)[0];assert.equal(retry.enemies[0].savedDamage.hp,enemy.hp);assert.equal(retry.enemies[0].savedDamage.bodyArmor,enemy.bodyArmor);});
test('an escaped Collector does not recover the final quest object',()=>{const s=readyForge();const q=s.legendaryBlacksmith.quests[3];q.status='active';q.survivors=q.encounter.enemies.map((_,i)=>i);s.legendaryBlacksmith.freeUse=false;s.legendaryBlacksmith.rewardId=null;const site=getBlacksmithQuestEncounters(s)[0];s.position={x:site.x,y:site.y};startBattle(s,site.id);s.battle.units.filter(u=>u.side==='enemy').forEach(u=>{u.hp=0;u.alive=false;if(u.champion)u.escaped=true;});resolveBattle(s);finishBattle(s);assert.equal(q.status,'active');assert.deepEqual(q.survivors,[0]);assert.deepEqual(validateSave(s),s);});
test('full transfer retains recipient design, all bonuses, original wear and immutable identity across reload and another weapon class',()=>{const s=readyForge();const donor=createFamedItemId('arming-sword',143,3);stash(s,[donor,'greatsword']);const expected=profile(getItem(donor));const {r}=forge(s,0,1,'transfer');const i=getItem(r.itemId);assert.equal(i.visual,getItem('greatsword').visual);assert.deepEqual(i.forgeProfile,expected);assert.equal(Object.isFrozen(i),true);s.gold=5000;stash(s,[i.id,'spear']);const next=forge(s,0,1,'transfer').r;assert.deepEqual(getItem(next.itemId).forgeProfile,expected);assert.ok(next.itemId.startsWith('forge4:'));});
test('named merging inherits whole affixes within slot limits and repeated quotes cannot reroll or double-spend',()=>{
 const s=readyForge();s.gold=50000;let successes=0;
 for(let seed=0;seed<24;seed++){
  s.cargo={iron:10,timber:10,wool:10};
  const a=createFamedItemId('arming-sword',seed,7),b=createFamedItemId('greatsword',seed+42,7);stash(s,[a,b]);
  const q=getReforgeQuote(s,0,1,'merge');assert.deepEqual(getReforgeQuote(s,0,1,'merge'),q);
  if(!q.ok){const before=structuredClone(s);assert.equal(reforgeItem(s,q).ok,false);assert.deepEqual(s,before);continue;}
  successes++;assert.ok(q.additions.length>=1&&q.additions.length<=3);
  assert.ok(q.result.forgeAffixes.prefixes.length<=2);assert.ok(q.result.forgeAffixes.suffixes.length<=2);
  assert.deepEqual(q.result.forgeAffixes.foundation,q.recipientAffixes.foundation);
  for(const kind of ['prefixes','suffixes'])for(const old of q.recipientAffixes[kind]){
   const after=q.result.forgeAffixes[kind].find(a=>a.id===old.id);assert.ok(after);
   for(const [key,n]of Object.entries(old.profile))assert.ok(after.profile[key]>=n);
  }
  assert.equal(reforgeItem(s,q).ok,true);assert.equal(reforgeItem(s,q).ok,false);assert.deepEqual(validateSave(s),s);
 }
 assert.ok(successes>=20);
});
test('armor and shield transfer preserves absolute damage, throwing transfer never refills ammunition',()=>{const s=readyForge();s.gold=5000;for(const [base,target] of [['mail-shirt','plate-harness'],['round-shield','kite-shield']]){const donor=createFamedItemId(base,42,3);stash(s,[donor,target]);s.inventoryCondition[1]-=15;const old=condition(target);const {q}=forge(s,0,1,'transfer');assert.equal(q.condition,condition(q.resultId)-(old-(old-15)));}const throwing=ITEMS.find(i=>i.throwing);stash(s,[createFamedItemId(throwing.id,4,3),throwing.id]);s.inventoryCondition[1]=1;assert.equal(forge(s,0,1,'transfer').q.condition,1);});
test('forge transactions fail atomically for stale inventory, insufficient gold, wrong category, wrong mode and duplicate copies',()=>{const s=readyForge();stash(s,[createFamedItemId('arming-sword',19,3),'greatsword']);const q=getReforgeQuote(s,0,1,'transfer');s.inventoryCondition[0]=1;const before=structuredClone(s);assert.equal(reforgeItem(s,q).ok,false);assert.deepEqual(s,before);s.inventoryCondition[0]=null;s.legendaryBlacksmith.freeUse=false;s.legendaryBlacksmith.forgeSerial=1;s.gold=0;const poor=getReforgeQuote(s,0,1,'transfer'),beforePoor=structuredClone(s);assert.equal(reforgeItem(s,poor).ok,false);assert.deepEqual(s,beforePoor);assert.equal(getReforgeQuote(s,0,0,'transfer').ok,false);assert.equal(getReforgeQuote(s,0,1,'merge').ok,false);s.inventory[1]='mail-shirt';assert.equal(getReforgeQuote(s,0,1,'transfer').ok,false);});
test('every catalog named roll yields a bounded typed profile, and percentage plus unique legacy damage is reconstructed exactly',()=>{for(const base of ITEMS.filter(i=>['weapon','armor','helmet','shield'].includes(i.slot)))for(const version of (base.ranged?[1,2,3,4]:[1,2,3])){const item=getItem(createFamedItemId(base.id,73,version)),p=profile(item);assert.ok(p,`${base.id} v${version}`);if(!Object.keys(p).length)continue;const rebuilt=getItem(encodeForgeItem(base.id,p,catalog));assert.ok(rebuilt);if(base.slot==='weapon'){assert.equal(rebuilt.damageMin,Math.min(300,item.damageMin),`${base.id} v${version} min`);assert.equal(rebuilt.damageMax,Math.min(300,item.damageMax),`${base.id} v${version} max`);}if(['armor','helmet'].includes(base.slot))assert.equal(rebuilt.armor,Math.min(base.slot==='armor'?650:500,item.armor),`${base.id} v${version}`);}});
test('forged gear supports actual equip, combat save, stow, resale and buyback',()=>{const s=readyForge();s.gold=50000;stash(s,[createFamedItemId('mail-shirt',42,3),'plate-harness']);s.inventoryCondition[1]-=19;const {r}=forge(s,0,1,'transfer');assert.equal(equipItem(s,'captain',r.itemId).ok,true);assert.equal(unequipItem(s,'captain','armor').ok,true);assert.equal(sellItem(s,r.itemId).ok,true);assert.equal(buyItem(s,r.itemId).ok,true);assert.equal(equipItem(s,'captain',r.itemId).ok,true);s.position={x:440,y:520};assert.equal(startBattle(s,'quarry-camp').ok,true);assert.deepEqual(validateSave(s),s);});
test('malformed identities and inconsistent quest progress are rejected without changing the source save',()=>{const id=encodeForgeItem('mail-shirt',{armorPct:20},catalog);for(const bad of [id.replace(':k.',':0k.'),id+'x',id.replace('mail-shirt','war-horse'),'forge1:mail-shirt:'+Array(FORGE_KEYS.length).fill('zzzz').join('.')])assert.equal(getItem(bad),undefined);const s=readyForge();for(const mutate of [x=>x.legendaryBlacksmith.freeUse=false,x=>x.legendaryBlacksmith.rewardId=createFamedItemId('spear',1),x=>x.legendaryBlacksmith.quests[2].survivors=[0],x=>x.legendaryBlacksmith.quests[1].encounter.enemies[0].name='Forged guard']){const bad=structuredClone(s);mutate(bad);const before=structuredClone(bad);assert.throws(()=>validateSave(bad));assert.deepEqual(bad,before);}});
test('a Collector killed before retreat remains dead and the remaining guards can complete the objective',()=>{const s=readyForge();const q=s.legendaryBlacksmith.quests[3];q.status='active';q.survivors=q.encounter.enemies.map((_,i)=>i);s.legendaryBlacksmith.freeUse=false;s.legendaryBlacksmith.rewardId=null;let site=getBlacksmithQuestEncounters(s)[0];s.position={x:site.x,y:site.y};startBattle(s,site.id);const collector=s.battle.units.find(u=>u.champion);collector.hp=0;collector.alive=false;retreatBattle(s);finishBattle(s);assert.equal(q.survivors.includes(0),false);site=getBlacksmithQuestEncounters(s)[0];startBattle(s,site.id);assert.deepEqual(validateSave(s),s);s.battle.units.filter(u=>u.side==='enemy').forEach(u=>{u.hp=0;u.alive=false;});resolveBattle(s);finishBattle(s);assert.equal(q.status,'ready');assert.deepEqual(validateSave(s),s);});
test('a real ordinary contract remains untouched through the material side quest and travel/save to its combat objective',async()=>{const {acceptContract,activateMapTarget}=await import('../src/engine.js');const {findOffer}=await import('./helpers/contract-offers.js');const s=discovered();const offer=findOffer(s,'courier','ironford');assert.equal(acceptContract(s,'ironford',offer.id).ok,true);const contract=structuredClone(s.contract);assert.equal(acceptBlacksmithQuest(s,1).ok,true);s.cargo.iron=8;s.cargo.timber=6;s.supplies.tools=10;assert.equal(turnInBlacksmithQuest(s,1).ok,true);assert.deepEqual(s.contract,contract);assert.equal(acceptBlacksmithQuest(s,2).ok,true);const site=getBlacksmithQuestEncounters(s)[0];assert.equal(activateMapTarget(s,'blacksmith',site.id).ok,true);assert.equal(s.destinationAction.type,'blacksmith');assert.deepEqual(validateSave(s),s);assert.deepEqual(s.contract,contract);});
test('inactive ranged and throwing enhancements survive a complete package transfer and reactivate on suitable gear',()=>{const s=readyForge();s.gold=5000;const original=encodeForgeItem('hunting-bow',{damagePct:20,range:1,accuracy:10},catalog);stash(s,[original,'greatsword']);const first=forge(s,0,1,'transfer').r;assert.equal(getItem(first.itemId).range,getItem('greatsword').range);assert.equal(getItem(first.itemId).forgeProfile.range,1);stash(s,[first.itemId,'hunting-bow']);const next=forge(s,0,1,'transfer').r;assert.equal(getItem(next.itemId).range,getItem('hunting-bow').range+1);});

test('ranged-only prefix donors cannot consume a merge on melee named recipients',()=>{
 const s=readyForge();
 const donor=encodeBoundedForgeItem('hunting-bow',{locked:false,foundation:{},prefixes:[{id:'longshot',profile:{rangedReach:1}},{id:'trueflight',profile:{rangedHit:8}}],suffixes:[]},catalog);
 stash(s,[donor,createFamedItemId('greatsword',42,3)]);
 const before=structuredClone(s),quote=getReforgeQuote(s,0,1,'merge');
 assert.equal(quote.ok,false);assert.match(quote.message,/no applicable improvement/);
 assert.deepEqual(s,before);
 stash(s,[donor,'greatsword']);
 const transferred=forge(s,0,1,'transfer').r.itemId;
 assert.ok(getItem(transferred).bonuses.every(row=>row.value.includes('inactive')));
 stash(s,[transferred,'hunting-bow']);
 const restored=getItem(forge(s,0,1,'transfer').r.itemId);
 assert.ok(restored.bonuses.every(row=>!row.value.includes('inactive')));
 assert.deepEqual(restored.forgeProfile,getItem(donor).forgeProfile);
});
