import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import * as m from '../src/engine.js';
import {NAMED_WEAPONS,NAMED_WEAPON_DESIGNS} from '../src/named-weapons.js';
import {NAMED_WEAPON_ART} from '../src/named-weapon-art.js';
import {equipmentSkills,weaponSkillFamily,COMBAT_SKILLS} from '../src/combat-skills.js';
import {equipmentCatalogHTML} from '../src/equipment-catalog.js';
import {townGearTheme} from '../src/town-facilities.js';
import {getItemDetails} from '../src/item-details.js';
import {itemImage,portraitHTML} from '../src/portraits.js';

function battle(id,shield=null){const state=m.createGame(51),item=m.getItem(id);state.inventory.push(id);state.inventoryCondition.push(item.throwing?m.throwingCapacity(id):null);assert.equal(m.equipItem(state,'captain',id).ok,true);if(shield){state.inventory.push(shield);state.inventoryCondition.push(m.shieldMaximum(shield));m.equipItem(state,'captain',shield);}const site=m.getCampSites(state)[0];state.position={x:site.x,y:site.y};m.startBattle(state,site.id);const b=state.battle;for(const t of b.field.tiles){t.terrain='open';t.height=0;}const at=(id,q,r)=>Object.assign(b.units.find(u=>u.id===id),{q,r});const actor=at('captain',2,2);at('guard',0,1);at('scout',0,3);const target=at('enemy-1',item.ranged?4:3,2);at('enemy-2',11,5);at('enemy-3',12,6);b.activeId=actor.id;b.turnIndex=b.turnOrder.indexOf(actor.id);return{state,b,actor,target,at};}
function skillFatigue(id){for(let seed=0;seed<1000;seed++){const item=m.getItem(m.createFamedItemId(id,seed));if(item.rollModifiers.includes('skill-fatigue'))return item;}assert.fail('Skill fatigue missing '+id);}
const namedId=(id)=>m.createFamedItemId(id,7913);

test('the source manifest covers every concrete named weapon except the explicitly deferred handgonne',()=>{
 const manifest=JSON.parse(readFileSync(new URL('../assets/named-weapons-source.json',import.meta.url)));assert.equal(manifest.imported,46);assert.equal(manifest.definitions.length,46);assert.equal(manifest.assets.length,46);assert.deepEqual(manifest.excluded.map(r=>r.path.split('/').at(-1)).sort(),['named_handgonne.nut','named_weapon.nut']);assert.equal(NAMED_WEAPONS.length,47);assert.equal(new Set(NAMED_WEAPONS.map(i=>i.id)).size,47);assert.ok(!m.ITEMS.some(i=>/handgonne|handgun/i.test(i.name+' '+i.id)));
 for(const asset of manifest.assets){const art=NAMED_WEAPON_ART[asset.id];for(const [field,hash]of[['icon','iconSha256'],['portrait','portraitSha256']])assert.equal(createHash('sha256').update(Buffer.from(art[field].split(',')[1],'base64')).digest('hex'),asset[hash]);assert.ok(asset.brush.includes('named'));assert.deepEqual(art.grip,[-asset.brushBounds[0],-asset.brushBounds[2]],'grip must use the flipped image origin, not its upper bound');}
});

test('all imported designs and alternate rolls have real art, a valid skill family, two modifiers and stable unrolled baselines',()=>{
 for(const design of NAMED_WEAPON_DESIGNS){const catalog=m.getItem(design.id);assert.equal(catalog.rarity,'named');assert.equal(catalog.rollModifiers.length,2);assert.ok(Object.isFrozen(design.sourceStats)&&Object.isFrozen(design.namePool));assert.ok(weaponSkillFamily(catalog));assert.ok(equipmentSkills(catalog).length);assert.equal(itemImage(catalog),NAMED_WEAPON_ART[design.id].icon);assert.ok(portraitHTML({seed:42,name:'Test'},{weapon:catalog}).includes(NAMED_WEAPON_ART[design.id].portrait));for(let seed=0;seed<128;seed++){const item=m.getItem(m.createFamedItemId(design.id,seed,2));assert.equal(item.rollModifiers.length,2);assert.equal(new Set(item.rollModifiers).size,2);assert.equal(item.price,Math.min(20000,Math.round(design.sourceStats.price*2.4)));assert.ok(item.fatigue<=design.sourceStats.fatigue);if(!item.rollModifiers.includes('damage')){assert.equal(item.damageMin,design.sourceStats.damageMin);assert.equal(item.damageMax,design.sourceStats.damageMax);}if(!item.rollModifiers.includes('skill-fatigue'))assert.equal(item.fatigueOnSkillUse,0);assert.equal(itemImage(item),itemImage(catalog));assert.deepEqual(m.getItem(item.id),item);}}
 const html=equipmentCatalogHTML('named-weapons');assert.equal((html.match(/data-item-source="catalog"/g)||[]).length,47);assert.match(html,/Impaler/);assert.doesNotMatch(html.replace(/src="data:[^"]+"/g,'src="image"'),/undefined|NaN|handgonne/i);
});

test('Impaler is a genuine named crossbow with its own two modifiers, reload and bolt skill',()=>{
 const item=m.getItem('impaler');assert.equal(item.name,'Impaler');assert.equal(item.rarity,'named');assert.ok(item.sourceNamedWeapon);assert.equal(weaponSkillFamily(item),'crossbow');assert.equal(item.rollModifiers.length,2);assert.ok(item.ranged&&item.twoHanded&&item.reloadTurns===1);assert.match(m.getItem(namedId('impaler')).name,/^\w+ Impaler of /);assert.equal(m.getItem(m.createFamedItemId('impaler',0,4)).name,'Impaler');const {state,b,actor,target}=battle('impaler');actor.rangedSkill=200;target.equipment.armor='mail-shirt';target.bodyArmor=100;target.maxBodyArmor=110;target.equipment.helmet='iron-helm';target.headArmor=100;target.maxHeadArmor=105;target.hp=target.maxHp=250;actor.skillPreference='damage';const ammo=state.supplies.ammo;m.advanceBattle(state);assert.equal(b.lastEvent.skillName,'Piercing Bolt');assert.equal(actor.reload,1);assert.equal(state.supplies.ammo,ammo-1);assert.equal(actor.ap,6);const ap=actor.ap;m.advanceBattle(state);assert.equal(b.lastEvent.skillName,'Reload');assert.equal(actor.ap,ap-4);assert.equal(actor.reload,0);assert.deepEqual(m.validateSave(structuredClone(state)),state);
});

test('every named weapon can be equipped, stowed and loaded into a valid new battle',()=>{
 for(const design of NAMED_WEAPON_DESIGNS){const id=namedId(design.id),{state}=battle(id);assert.deepEqual(m.validateSave(structuredClone(state)),state,design.id);m.advanceBattle(state);assert.deepEqual(m.validateSave(structuredClone(state)),state,design.id);const peaceful=m.createGame(16),item=m.getItem(id);peaceful.inventory.push(id);peaceful.inventoryCondition.push(item.throwing?m.throwingCapacity(id):null);m.equipItem(peaceful,'captain',id);m.unequipItem(peaceful,'captain','weapon');assert.ok(peaceful.inventory.includes(id));assert.deepEqual(m.validateSave(structuredClone(peaceful)),peaceful);}
});

test('named fencing Lunge advances one hex and charges AP/fatigue once, before Sword Training',()=>{
 const item=skillFatigue('bb-named-fencing-sword');for(const mastery of [false,true]){const {state,b,actor,target,at}=battle(item.id);at(target.id,4,2);actor.meleeSkill=200;actor.skillPreference='damage';target.hp=target.maxHp=250;target.bodyArmor=target.headArmor=0;if(mastery){actor.perks.push('sword-training');state.party[0].level=2;state.party[0].perks.push('sword-training');}const origin={q:actor.q,r:actor.r};m.advanceBattle(state);assert.equal(b.lastEvent.skillName,'Lunge');assert.equal(b.lastEvent.type,'attack');assert.deepEqual(b.lastEvent.moveFrom,origin);assert.equal(Math.abs(actor.q-origin.q)+Math.abs(actor.r-origin.r),1);assert.equal(actor.ap,mastery?6:5);const cost=25+item.fatigueOnSkillUse;assert.equal(actor.fatigue,mastery?Math.ceil(cost*.75):cost);assert.ok(b.lastEvent.hpDamage>0);assert.deepEqual(m.validateSave(structuredClone(state)),state);}
});

test('Lunge cannot step through blockers or cliffs, cannot start in melee and respects its full fatigue cost',()=>{
 for(const reason of ['blocked','cliff','engaged','fatigue']){const {state,b,actor,target,at}=battle(namedId('bb-named-fencing-sword'));at(target.id,4,2);actor.skillPreference='damage';if(reason==='blocked'){at('guard',3,2);}if(reason==='cliff')b.field.tiles.find(t=>t.q===3&&t.r===2).height=3;if(reason==='engaged')at('enemy-2',2,3);if(reason==='fatigue'){actor.fatigue=actor.maxFatigue-(25+(m.getItem(actor.equipment.weapon).fatigueOnSkillUse??0))+1;actor.turnStartedRound=b.round;}m.advanceBattle(state);assert.notEqual(b.lastEvent.skillName,'Lunge',reason);}
});

test('Spearwall intercepts Lunge before its thrust, without granting a free attack',()=>{
 const {state,b,actor,target,at}=battle(namedId('bb-named-fencing-sword'));at(target.id,4,2);actor.meleeSkill=200;actor.skillPreference='damage';target.equipment.weapon='spear';target.spearwallActive=true;target.meleeSkill=200;b.rng=1972;const hp=target.hp;m.advanceBattle(state);assert.equal(b.lastEvent.skillName,'Lunge');assert.equal(b.lastEvent.type,'hold');assert.equal(target.hp,hp);assert.equal(actor.q,2);assert.equal(actor.r,2);assert.equal(b.lastEvent.reactions[0].skillName,'Spearwall');assert.equal(actor.ap,5);assert.deepEqual(m.validateSave(structuredClone(state)),state);
});

test('named spetums expose Spearwall with two-hex interception and a six-AP stance',()=>{
 const id=namedId('bb-named-spetum'),{state,b,actor,target,at}=battle(id);assert.equal(weaponSkillFamily(m.getItem(id)),'spear');assert.equal(equipmentSkills(m.getItem(id)).find(s=>s.id==='spearwall').ap,6);at(target.id,5,2);actor.spearwallActive=true;actor.meleeSkill=200;target.meleeDefense=0;b.activeId=target.id;b.turnIndex=b.turnOrder.indexOf(target.id);b.rng=1972;const before={q:target.q,r:target.r};m.advanceBattle(state);assert.deepEqual({q:target.q,r:target.r},before);assert.equal(b.lastEvent.reactions[0].skillName,'Spearwall');assert.equal(actor.fatigue,5);assert.deepEqual(m.validateSave(structuredClone(state)),state);
});

test('Split Shield always strikes only durability in audited battles; old battles keep the prior rules',()=>{
 const item=skillFatigue('wood-axe');const {state,b,actor,target}=battle(item.id);actor.meleeSkill=0;actor.skillPreference='damage';target.meleeDefense=200;target.equipment.armor='plate-harness';target.bodyArmor=target.maxBodyArmor=300;target.equipment.helmet='bascinet';target.headArmor=target.maxHeadArmor=175;target.hp=target.maxHp=250;target.equipment.shield='kite-shield';target.shieldDurability=target.maxShieldDurability=m.shieldMaximum('kite-shield');target.shieldWallActive=true;b.rng=0;const old=structuredClone(state);delete old.battle.weaponAuditVersion;const before={hp:target.hp,body:target.bodyArmor,head:target.headArmor,morale:target.morale};m.advanceBattle(state);assert.equal(b.lastEvent.skillName,'Split Shield');assert.equal(b.lastEvent.type,'attack');assert.deepEqual({hp:target.hp,body:target.bodyArmor,head:target.headArmor,morale:target.morale},before);assert.equal(b.lastEvent.hpDamage,0);assert.equal(b.lastEvent.armorDamage,0);assert.equal(b.lastEvent.head,false);assert.ok(b.lastEvent.shieldDamage>0);assert.equal(actor.fatigue,18+item.fatigueOnSkillUse);assert.equal(actor.ap,5);m.advanceBattle(old);assert.notEqual(old.battle.lastEvent.type,'attack','legacy hit roll still misses at this seed');assert.equal(m.validateSave(structuredClone(old)).battle.weaponAuditVersion,undefined);
});

test('named offers stay rare, correctly themed, and survive purchase, sale and repeated import',()=>{
 let offers=0,found;for(let seed=1;seed<=20;seed++){const state=m.createGame(seed);for(const town of m.SETTLEMENTS){state.position={x:town.x,y:town.y};const rare=m.getMarket(state).equipment.filter(r=>r.stock>0&&m.getItem(r.itemId).sourceNamedWeapon);assert.ok(rare.length<=1);for(const row of rare){offers++;const item=m.getItem(row.itemId);assert.ok(!['ancient','greenskin'].includes(item.sourceCulture));if(item.region)assert.equal(item.region,townGearTheme(town));found??={state:structuredClone(state),row};}}}assert.ok(offers>0);assert.ok(offers<20*m.SETTLEMENTS.length*.1);const {state,row}=found;state.gold=50000;assert.equal(m.buyItem(state,row.itemId).ok,true);const item=m.getItem(row.itemId);assert.equal(m.sellItem(state,row.itemId).ok,true);assert.equal(m.buyItem(state,row.itemId).ok,true);assert.deepEqual(m.getItem(row.itemId),item);assert.deepEqual(m.validateSave(structuredClone(state)),state);
});

test('sourced champion weapons are equipped and guaranteed in victory loot, with fixed IDs across reload',()=>{
 let found;for(let seed=1;seed<=80&&!found;seed++){const state=m.createGame(seed);for(const site of m.getCampSites(state)){if(site.enemies.some(e=>e.champion&&m.getItem(e.championItemId)?.sourceNamedWeapon)){found={state,site};break;}}}assert.ok(found);const {state,site}=found;state.position={x:site.x,y:site.y};assert.equal(m.startBattle(state,site.id).ok,true);const champion=state.battle.units.find(u=>u.champion&&m.getItem(u.championItemId)?.sourceNamedWeapon),trophy=champion.championItemId;assert.equal(champion.equipment.weapon,trophy);assert.deepEqual(m.validateSave(structuredClone(state)),state);for(const enemy of state.battle.units.filter(u=>u.side==='enemy')){enemy.hp=0;enemy.alive=false;}m.advanceBattle(state);assert.equal(state.battle.status,'victory');assert.ok(state.battle.loot.items.includes(trophy));assert.deepEqual(m.validateSave(structuredClone(state)),state);
});

test('new source weapons and Lunge resolve deterministically with save reloads between actions',()=>{
 for(const id of ['impaler','bb-named-fencing-sword','bb-named-spetum','bb-named-two-handed-mace','bb-named-crypt-cleaver','bb-named-throwing-axe']){let {state}=battle(namedId(id));const instant=structuredClone(state);assert.equal(m.resolveBattle(instant).ok,true);let steps=0;while(state.battle.status==='active'&&steps++<2000){m.advanceBattle(state);state=m.validateSave(structuredClone(state));}assert.notEqual(state.battle.status,'active',id);assert.deepEqual(state,instant,id);}
});
