import test from 'node:test';
import assert from 'node:assert/strict';
import * as e from '../src/engine.js';
import {retinueHTML,battleResultsHTML} from '../src/campaign-ui.js';
const game=()=>{const s=e.createGame(7391);e.buyFood(s,1);s.gold=100000;return s;};
const hire=(s,id)=>assert.equal(e.hireRetinueMember(s,id).ok,true);
const save=s=>e.validateSave(JSON.parse(JSON.stringify(s)));
function victory(s){const c=e.getCampSites(s)[0];s.position={x:c.x,y:c.y};assert.equal(e.startBattle(s,c.id).ok,true);for(const u of s.battle.units)if(u.side==='enemy'){u.hp=0;u.alive=false;}const a=s.battle.units.find(u=>u.side==='company');s.battle.activeId=a.id;s.battle.turnIndex=s.battle.turnOrder.indexOf(a.id);e.advanceBattle(s);assert.equal(s.battle.status,'victory');}
for(const m of e.RETINUE_MEMBERS){
 test(`${m.name}: one-time hire is save-safe and leaves formation and roster intact`,()=>{const s=game(),party=structuredClone(s.party),formation=structuredClone(s.formation);hire(s,m.id);assert.equal(s.gold,100000-m.cost);assert.deepEqual(s.party,party);assert.deepEqual(s.formation,formation);const before=structuredClone(s);assert.equal(e.hireRetinueMember(s,m.id).ok,false);assert.deepEqual(s,before);assert.equal(e.hasRetinue(save(s),m.id),true);});
}
test('failed hire and upgrade actions are atomic',()=>{for(const change of [s=>s.gold=0,s=>s.position={x:1,y:1},s=>s.gameOver=true,s=>s.battle={}]){const s=game();change(s);const before=structuredClone(s);assert.equal(e.hireRetinueMember(s,'scout').ok,false);assert.equal(e.upgradeScout(s).ok,false);assert.deepEqual(s,before);}const s=game(),before=structuredClone(s);assert.equal(e.hireRetinueMember(s,'invalid').ok,false);assert.equal(e.upgradeScout(s).ok,false);assert.deepEqual(s,before);});
test('old saves default inactive; malformed hires, tiers, carries and cargo origins reject',()=>{const old=game();delete old.retinue;assert.deepEqual(save(old).retinue.members,[]);for(const change of [s=>s.retinue.members=null,s=>s.retinue.members={},s=>s.retinue.members=['scout','scout'],s=>s.retinue.members=['fake'],s=>s.retinue.scoutLevel=2,s=>s.retinue.scoutLevel=null,s=>s.retinue.foodRemainder=5,s=>s.retinue.toolRemainder=-1,s=>s.retinue.repairRemainder=1.5,s=>s.cargoOrigins={grain:[{townId:'fake',count:1}]},s=>s.cargoOrigins={grain:[{townId:'oakwatch',count:1}]}]){const s=game();change(s);assert.throws(()=>save(s));}});
test('quartermaster saves fractions through daily reloads, including mount upkeep',()=>{for(const mounted of [false,true]){let s=game();hire(s,'quartermaster');if(mounted)s.party[0].equipment.mount='riding-horse';const raw=s.party.length+(mounted?e.getItem('riding-horse').foodUpkeep:0);assert.equal(e.getDailyFood(s),raw*4/5);s.food=100;for(let i=0;i<5;i++){assert.equal(e.tick(s,24).ok,true);s=save(s);}assert.equal(s.food,100-raw*4);assert.equal(s.retinue.foodRemainder,0);}});
test('surgeon improves medicated and bare rest and actual doctor price',()=>{for(const medicine of [0,1]){const s=game();hire(s,'surgeon');for(const p of s.party)p.hp=1;s.supplies.medicine=medicine;s.supplies.tools=0;assert.equal(e.camp(s).ok,true);assert.equal(s.party[0].hp,medicine?31:11);assert.equal(s.supplies.medicine,0);save(s);}const s=game();hire(s,'surgeon');const p=s.party[0],max=e.getCompanyStats(p).maxHp;p.hp=max-7;const q=e.getTownServiceQuote(s,'doctor',p.id);assert.equal(q.totalCost,6);const gold=s.gold;assert.equal(e.useTownService(s,'doctor',p.id).ok,true);assert.equal(s.gold,gold-6);assert.equal(p.hp,max);});
test('armorer repairs all protection, saves fractional output and never works with no tools',()=>{const s=game();hire(s,'armorer');const p=s.party[0];p.equipment.armor='fantasy-grand-steel-armor';p.armorDurability.body=0;s.supplies.tools=3;assert.equal(e.camp(s).ok,true);assert.equal(p.armorDurability.body,125);assert.equal(s.supplies.tools,0);assert.equal(s.retinue.toolRemainder,1);assert.equal(s.retinue.repairRemainder,0);save(s);const before=p.armorDurability.body;assert.equal(e.camp(s).ok,true);assert.equal(p.armorDurability.body,before);});
test('Broker pays journeys more, prevents local flip loops and preserves origins on reload',()=>{let s=game();const base=e.getMarket(s).goods.find(g=>g.goodId==='timber');assert.equal(e.buyGood(s,'timber',2).ok,true);hire(s,'broker');let quote=e.getMarket(s).goods.find(g=>g.goodId==='timber');assert.equal(quote.sellPrice,base.sellPrice);assert.equal(quote.brokerLocal,true);const localGold=s.gold;assert.equal(e.sellGood(s,'timber').ok,true);assert.equal(s.gold,localGold+base.sellPrice);s=save(s);const input=structuredClone(s),restored=e.validateSave(input);restored.cargoOrigins.timber[0].count=0;assert.equal(input.cargoOrigins.timber[0].count,1);const destination=e.SETTLEMENTS.find(t=>t.id==='highpass');s.position={x:destination.x,y:destination.y};const plain=structuredClone(s);plain.retinue.members=[];plain.retinue.scoutLevel=0;const foreignBase=e.getMarket(plain).goods.find(g=>g.goodId==='timber').sellPrice;quote=e.getMarket(s).goods.find(g=>g.goodId==='timber');assert.equal(quote.sellPrice,Math.floor(foreignBase*1.5));assert.equal(quote.brokerLocal,false);const gold=s.gold;assert.equal(e.sellGood(s,'timber').ok,true);assert.equal(s.gold,gold+quote.sellPrice);assert.equal(s.cargoOrigins.timber,undefined);save(s);});
test('Broker mixed cargo sells foreign first and weighted bulk payout agrees',()=>{const s=game();hire(s,'broker');s.cargo.timber=2;assert.equal(e.buyGood(s,'timber',2).ok,true);const plain=structuredClone(s);plain.retinue.members=[];const base=e.getMarket(plain).goods.find(g=>g.goodId==='timber').sellPrice,boost=Math.floor(base*1.5);const gold=s.gold;assert.equal(e.sellGood(s,'timber',3).ok,true);assert.equal(s.gold,gold+boost*2+base);assert.equal(s.cargo.timber,1);assert.equal(s.cargoOrigins.timber[0].count,1);assert.equal(e.getMarket(s).goods.find(g=>g.goodId==='timber').brokerLocal,true);save(s);});
test('Broker changes equipment sale quotes and receipts, never buying price',()=>{const s=game(),normal=e.getMarket(s).equipment.find(q=>q.itemId==='bandages');hire(s,'broker');const row=e.getMarket(s).equipment.find(q=>q.itemId==='bandages');assert.equal(row.buyPrice,normal.buyPrice);assert.equal(row.sellPrice,Math.min(row.buyPrice-1,Math.floor(normal.sellPrice*1.1)));const gold=s.gold,index=s.inventory.indexOf('bandages');if(index<0){s.inventory.push('bandages');s.inventoryCondition.push(null);}assert.equal(e.sellItem(s,'bandages').ok,true);assert.equal(s.gold,gold+row.sellPrice);});
test('Scout charges once, stacks movement modifiers and restores its upgraded tier',()=>{const s=game();hire(s,'scout');assert.equal(e.getCompanyTravelMultiplier(s),1.1);e.buyCompanyCart(s);assert.equal(e.getCompanyTravelMultiplier(s),.95*1.1);const gold=s.gold;assert.equal(e.upgradeScout(s).ok,true);assert.equal(s.gold,gold-10000);assert.equal(e.getBandAwarenessMultiplier(s),.67);assert.equal(e.getScoutLevel(save(s)),2);const before=structuredClone(s);assert.equal(e.upgradeScout(s).ok,false);assert.deepEqual(s,before);});
test('upgraded Scout reduces actual enemy acquisition and pursuit leash',()=>{for(const upgraded of [false,true])for(const hunting of [false,true]){const s=game();hire(s,'scout');if(upgraded)e.upgradeScout(s);for(const p of Object.values(s.factionPatrols)){p.troops=[];p.defeatedUntil=200;}for(const [id,p] of Object.entries(s.bands))if(id!=='road-thieves')p.defeatedUntil=200;s.position={x:450,y:460};const band=s.bands['road-thieves'];Object.assign(band,{x:450+(hunting?200:100),y:460,defeatedUntil:0,behavior:hunting?'hunting-company':'patrolling',targetId:hunting?'company':null});e.tick(s,.25);assert.equal(band.behavior==='hunting-company',!upgraded);}});
test('Scavenger boosts displayed and awarded gold without changing drops',()=>{const s=game();hire(s,'scavenger');victory(s);s.battle.loot.gold=101;const items=structuredClone(s.battle.loot.items),gold=s.gold;assert.equal(e.getBattleLootGold(s),126);assert.match(battleResultsHTML(s),/<strong>126<\/strong>/);assert.deepEqual(s.battle.loot.items,items);assert.equal(e.finishBattle(s).ok,true);assert.equal(s.gold,gold+126);save(s);});
test('Drillmaster awards battle experience to survivors and reserve training on victory',()=>{const s=game();hire(s,'drillmaster');const reserve=s.party.at(-1);s.formation=s.formation.map(id=>id===reserve.id?null:id);s.reserveIds=[reserve.id,null,null];victory(s);for(const u of s.battle.units)if(u.side==='company')s.battle.xp[u.id]=100;assert.equal(e.getBattleExperience(s,reserve.id),15);const field=s.party[0];assert.equal(e.getBattleExperience(s,field.id),115);assert.match(battleResultsHTML(s),/115 experience/);assert.equal(e.finishBattle(s).ok,true);assert.equal(reserve.xp,15);assert.equal(field.level,2);assert.equal(field.xp,65);save(s);});
test('retinue cards expose clear costs, statuses and accessible on-demand hints',()=>{const s=game(),html=retinueHTML(s);assert.equal((html.match(/data-retinue-card=/g)||[]).length,9);assert.match(html,/role="tooltip" hidden/);assert.match(html,/6,000 crowns/);assert.match(html,/Travel &amp; supplies/);hire(s,'scout');assert.match(retinueHTML(s),/Upgrade Scout.*10,000/);e.upgradeScout(s);assert.match(retinueHTML(s),/Enemy awareness −33%/);assert.doesNotMatch(retinueHTML(s),/data-action="upgrade-scout"/);});

test('all specialists stack without changing ordinary daily wages',()=>{
 const s=game();for(const m of e.RETINUE_MEMBERS)hire(s,m.id);
 const wages=s.party.reduce((sum,p)=>sum+e.getCompanyStats(p).dailyWage,0),gold=s.gold;
 e.tick(s,24);assert.equal(s.gold,gold-wages);assert.equal(save(s).retinue.members.length,7);
});
test('Scout movement stacks with mounts and night and upgrade failures preserve state',()=>{
 const s=game();hire(s,'scout');s.party[0].equipment.mount='riding-horse';s.hour=22;
 assert.equal(e.getCompanyTravelMultiplier(s),(1+e.getCompanyTravelBonus(s))*.8*1.1);
 s.gold=9999;const before=structuredClone(s);assert.equal(e.upgradeScout(s).ok,false);assert.deepEqual(s,before);
});
test('Drillmaster keeps donation XP separate, awards no fallen XP and preserves level cap',()=>{
 const s=game();hire(s,'drillmaster');victory(s);s.battle.loot.items=['bandages'];s.battle.loot.itemConditions=[null];
 for(const u of s.battle.units)if(u.side==='company')s.battle.xp[u.id]=100;
 const share=e.getLootKeepQuote(s,[]);const field=s.party[0];e.finishBattle(s,{shareLootIndices:[0]});assert.equal(field.xp,65+share.xp);save(s);
 const capped=game();hire(capped,'drillmaster');victory(capped);const p=capped.party[0];p.level=30;p.xp=1499;
 capped.battle.xp[p.id]=100;const dead=capped.battle.units.find(u=>u.id===capped.party[1].id);dead.alive=false;dead.hp=0;
 assert.equal(e.getBattleExperience(capped,dead.id),0);e.finishBattle(capped);assert.equal(p.xp,1499);assert.equal(capped.party.some(p=>p.id===dead.id),false);save(capped);
});
test('Armorer repairs attachments and both shields and reloads remaining savings',()=>{
 const s=game();hire(s,'armorer');const p=s.party[0];p.equipment.attachment='scale-mantle';p.equipment.shield='buckler';p.reserveEquipment.shield='buckler';
 p.armorDurability.attachment=0;p.armorDurability.shield=0;p.armorDurability.reserveShield=0;s.supplies.tools=20;
 e.camp(s);assert.equal(p.armorDurability.attachment,e.getItem('scale-mantle').armor);assert.equal(p.armorDurability.shield,e.shieldMaximum('buckler'));assert.equal(p.armorDurability.reserveShield,e.shieldMaximum('buckler'));
 const restored=save(s);assert.equal(restored.retinue.toolRemainder,s.retinue.toolRemainder);assert.equal(restored.retinue.repairRemainder,s.retinue.repairRemainder);
});
test('upgraded Scout still triggers combat on close enemy contact',()=>{
 const s=game();hire(s,'scout');e.upgradeScout(s);
 for(const p of Object.values(s.factionPatrols)){p.troops=[];p.defeatedUntil=200;}
 for(const [id,p] of Object.entries(s.bands))if(id!=='road-thieves')p.defeatedUntil=200;
 s.position={x:450,y:460};Object.assign(s.bands['road-thieves'],{x:470,y:460,defeatedUntil:0,behavior:'patrolling',targetId:null});
 e.tick(s,.25);assert.equal(s.battle?.campId,'road-thieves');
});
