import test from 'node:test';
import assert from 'node:assert/strict';
import {createGame,getCompanyStats,getTownEvent,getItem,getMountRewardEvents,shieldMaximum,SETTLEMENTS} from '../src/engine.js';
import {townActionsHTML,townStatusHTML} from '../src/campaign-ui.js';
function healthy(){const s=createGame(73);for(const p of s.party){p.hp=getCompanyStats(p).maxHp;for(const [part,slot] of [['body','armor'],['head','helmet'],['attachment','attachment'],['attachment2','attachment2'],['shield','shield']])p.armorDurability[part]=slot==='shield'?shieldMaximum(p.equipment.shield):getItem(p.equipment[slot])?.armor??0;}return s;}
test('healthy town company has trade/hiring but no unnecessary Doctor or Smithy',()=>{const s=healthy(),html=townActionsHTML(s,'oakwatch');assert.match(html,/data-action="market"/);assert.match(html,/data-action="recruit"/);assert.doesNotMatch(html,/data-action="doctor"|data-action="smithy"/);assert.equal(townActionsHTML(s,'ironford'),'');s.position={x:440,y:520};assert.equal(townActionsHTML(s,'oakwatch'),'');});
test('needed care remains visible independently, including unaffordable healing and second-layer or reserve-shield repairs',()=>{const s=healthy(),p=s.party[0];s.gold=0;p.hp--;let html=townActionsHTML(s,'oakwatch',true);assert.match(html,/data-action="doctor"/);assert.doesNotMatch(html,/data-action="smithy"/);p.hp++;p.level=4;p.perks=['layered-armor'];p.equipment.attachment2='scale-mantle';p.armorDurability.attachment2=79;html=townActionsHTML(s,'oakwatch');assert.doesNotMatch(html,/data-action="doctor"/);assert.match(html,/data-action="smithy"/);p.armorDurability.attachment2=80;p.reserveEquipment.shield='kite-shield';p.armorDurability.reserveShield=1;assert.match(townActionsHTML(s,'oakwatch'),/data-action="smithy"/);p.armorDurability.reserveShield=shieldMaximum('kite-shield');assert.doesNotMatch(townActionsHTML(s,'oakwatch'),/data-action="smithy"/);});
test('town status icons preserve event effects and time in accessible focusable tooltips',()=>{let s,event;for(let seed=1;seed<100;seed++){s=createGame(seed);event=getTownEvent(s,'oakwatch');if(event)break;}assert.ok(event);const html=townStatusHTML(s,'oakwatch');assert.match(html,/role="group" aria-label="Settlement status"/);assert.match(html,/type="button" class="town-status-icon/);assert.match(html,/aria-describedby="town-status-oakwatch-event"/);assert.ok(html.includes(event.name));assert.ok(event.effects.every(e=>html.includes(e)));assert.ok(html.includes(`Through day ${event.endDay}`));assert.doesNotMatch(html,/class="town-event|class="town-facilities|<article>/);assert.match(townStatusHTML(s,'ironford'),/aria-label="Blacksmith"/);});
test('rare mount status keeps its claim action at the reward town and hides it elsewhere',()=>{const s=createGame(73),reward=getMountRewardEvents(s).find(e=>!e.claimed);assert.ok(reward);s.day=reward.availableDay;s.hour=8;const t=SETTLEMENTS.find(t=>t.id===reward.townId);s.position={x:t.x,y:t.y};assert.match(townStatusHTML(s,t.id),/data-action="claim-mount-reward"/);s.position={x:440,y:520};assert.doesNotMatch(townStatusHTML(s,t.id),/data-action="claim-mount-reward"/);});
