import {test,expect} from '@playwright/test';
import {entombedCompany} from '../tests/fixtures/entombed-company.mjs';
const key='ashen-company-save-v1';
async function seed(page){const source=entombedCompany();await page.addInitScript(({key,text})=>{if(!localStorage.getItem(key))localStorage.setItem(key,text);},{key,text:JSON.stringify(source.state)});await page.goto('./');await page.locator('[data-action="blacksmith-later"]').click();return source;}
async function openRetirement(page,indices){await page.locator('#settings-button').click();await page.locator('[data-action="legacy-retire"]').click();await expect(page.locator('[data-action="legacy-review"]')).toBeDisabled();for(const [n,set] of indices.entries())for(const [slot,i] of Object.entries(set))if(i!==null)await page.locator(`[data-legacy-set="${n}"][data-legacy-slot="${slot}"]`).selectOption(String(i));await expect(page.locator('[data-action="legacy-review"]')).toBeEnabled();await page.locator('[data-action="legacy-review"]').click();}
test('iPad retirement selects three complete sets, confirms explicitly, backs up and persists entombed gear',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));const {state:source,indices}=await seed(page);await openRetirement(page,indices);
 await expect(page.getByText('This ends your current campaign and replaces its active save.')).toBeVisible();await page.getByRole('button',{name:'Keep playing'}).click();expect((await page.evaluate(key=>JSON.parse(localStorage.getItem(key)),key)).companyLegacy).toBeUndefined();await openRetirement(page,indices);
 const bounds=await page.locator('#modal').boundingBox();expect(bounds.width).toBeLessThanOrEqual(1024);expect(bounds.height).toBeLessThanOrEqual(768);await page.locator('[data-action="legacy-confirm"]').click();await expect(page.locator('#modal .legacy-panel')).toContainText('TOMB QUEST 1/3');
 const stored=await page.evaluate(key=>({active:JSON.parse(localStorage.getItem(key)),retired:JSON.parse(localStorage.getItem(key+'-retired'))}),key);expect(stored.active.day).toBe(1);expect(stored.active.companyLegacy.version).toBe(3);expect(stored.active.companyLegacy.sets).toHaveLength(3);expect(stored.active.inventory).not.toContain(source.inventory[0]);expect(stored.retired.inventory).toEqual(source.inventory);
 await expect(page.locator('[data-legacy-turnin="1"]')).toBeDisabled();await expect(page.locator('[data-legacy-tomb]')).toHaveCount(0);await page.reload();await page.locator('[data-tab="journal"]').first().click();await expect(page.locator('.legacy-journal')).toContainText('TOMB QUEST 1/3');await page.locator('#settings-button').click();const download=page.waitForEvent('download');await page.locator('[data-action="legacy-export-retired"]').click();expect((await download).suggestedFilename()).toBe('ashen-company-retired.json');expect(errors).toEqual([]);
});
test('failed active-save retirement write preserves the source and can be retried with all sets intact',async({page})=>{
 const {state:source,indices}=await seed(page);await openRetirement(page,indices);await page.evaluate(key=>{const original=Storage.prototype.setItem;let fail=true;Storage.prototype.setItem=function(k,v){if(k===key&&fail){fail=false;throw new DOMException('Quota reached','QuotaExceededError');}return original.call(this,k,v);};},key);
 await page.locator('[data-action="legacy-confirm"]').click();await expect(page.locator('#toast')).toContainText('Retirement was not applied');const current=await page.evaluate(key=>JSON.parse(localStorage.getItem(key)),key);expect(current.seed).toBe(source.seed);expect(current.companyLegacy).toBeUndefined();await expect(page.locator('[data-action="legacy-confirm"]')).toBeVisible();await page.locator('[data-action="legacy-confirm"]').click();await expect(page.locator('#modal .legacy-panel')).toContainText('TOMB QUEST 1/3');
});
test('set picker prevents copy reuse and frees a shield slot for a two-hander on touch layouts',async({page})=>{
 const {indices}=await seed(page);await page.locator('#settings-button').click();await page.locator('[data-action="legacy-retire"]').click();await page.locator('[data-legacy-set="0"][data-legacy-slot="mount"]').selectOption(String(indices[0].mount));await expect(page.locator(`[data-legacy-set="1"][data-legacy-slot="mount"] option[value="${indices[0].mount}"]`)).toHaveAttribute('disabled','');await page.locator('[data-legacy-set="0"][data-legacy-slot="weapon"]').selectOption(String(indices[1].weapon));await expect(page.locator('[data-legacy-set="0"][data-legacy-slot="shield"]')).toBeDisabled();await page.screenshot({path:'/tmp/entombed-set-picker.png'});
 for(const width of [1024,768,390]){await page.setViewportSize({width,height:768});const box=await page.locator('#modal').boundingBox();expect(box.width).toBeLessThanOrEqual(width);expect(box.height).toBeLessThanOrEqual(768);expect(await page.locator('#modal').evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);}
});
