import {test,expect} from '@playwright/test';import * as g from '../src/engine.js';import {entombedCompany} from '../tests/fixtures/entombed-company.mjs';
const key='ashen-company-save-v1';
function finalCompany(defeated=false){const {state,indices}=entombedCompany(),s=g.createLegacyCampaign(state,g.getLegacySetRetirementQuote(state,indices),91).state;Object.assign(s,{day:60,renown:300,shipmentLegacyThroughDay:60});Object.assign(s.companyLegacy,{stage:3,defeated});const t=g.SETTLEMENTS.find(t=>t.id==='ravenfell');s.position={x:t.x,y:t.y};return g.validateSave(s);}
async function load(page,s){await page.addInitScript(({key,text})=>{if(!localStorage.getItem(key))localStorage.setItem(key,text);},{key,text:JSON.stringify(s)});await page.goto('./');}
test('final tomb navigation starts a real nine-unit undead cavalry battle and preserves retreat on reload',async({page})=>{
 const s=finalCompany(),site=g.getLegacyTombEncounters(s)[0];s.position={x:site.x,y:site.y};const errors=[];page.on('pageerror',e=>errors.push(e.message));await load(page,s);await page.locator('[data-tab="journal"]').first().click();await page.locator('[data-legacy-tomb]').click();await expect(page.locator('.battle-view')).toBeVisible();await page.locator('[data-battle-speed="0"]').click();const active=await page.evaluate(key=>JSON.parse(localStorage.getItem(key)),key);expect(active.battle.encounterType).toBe('legacy-tomb');const enemies=active.battle.units.filter(u=>u.side==='enemy');expect(enemies).toHaveLength(9);expect(enemies.every(u=>u.equipment.mount&&u.undeadTraitsVersion===1)).toBe(true);for(let n=0;n<3;n++)expect(enemies[n].equipment.weapon).toBe(s.companyLegacy.sets[n].weapon.itemId);
 await page.locator('.battle-more summary').click();await page.locator('[data-action="retreat-battle"]').click();await page.locator('[data-action="confirm-retreat"]').click();await page.locator('[data-action="finish-battle"]').click();await page.reload();await page.locator('[data-tab="journal"]').first().click();await expect(page.locator('[data-legacy-tomb]')).toBeVisible();const saved=await page.evaluate(key=>JSON.parse(localStorage.getItem(key)),key);expect(saved.companyLegacy.guards).toHaveLength(9);expect(errors).toEqual([]);
});
test('final quest unveils exactly the third complete set, persists and cannot be claimed again',async({page})=>{
 const s=finalCompany(true),entries=Object.values(s.companyLegacy.sets[2]).filter(Boolean);await load(page,s);await page.locator('[data-tab="journal"]').first().click();await expect(page.locator('[data-legacy-turnin="3"]')).toBeEnabled();await page.locator('[data-legacy-turnin="3"]').click();await expect(page.locator('#modal .legacy-panel')).toContainText('All three sets have been unveiled');const saved=await page.evaluate(key=>JSON.parse(localStorage.getItem(key)),key);expect(saved.inventory.slice(-entries.length)).toEqual(entries.map(e=>e.itemId));expect(saved.inventoryCondition.slice(-entries.length)).toEqual(entries.map(e=>e.condition));await page.reload();await page.locator('[data-tab="journal"]').first().click();await expect(page.locator('[data-legacy-turnin]')).toHaveCount(0);expect((await page.evaluate(key=>JSON.parse(localStorage.getItem(key)),key)).inventory).toEqual(saved.inventory);
});

test('chronicle navigation exposes tomb scouting and its quest reward on the world map',async({page})=>{
 const s=finalCompany();const errors=[];page.on('pageerror',e=>errors.push(e.message));await load(page,s);await page.locator('[data-tab="journal"]').first().click();await page.locator('[data-legacy-tomb]').click();await page.getByRole('button',{name:'Pause travel',exact:true}).click();await expect(page.locator('[data-quest-travel="legacy-tomb"]')).toBeVisible();await expect(page.getByText('♞ 9 undead cavalry · set 3/3')).toBeVisible();await page.getByText('Tomb reward',{exact:true}).click();await expect(page.getByText('Guardians cannot flee. Their gear does not drop; report after victory to unveil one complete set, with its original bonuses and wear.')).toBeVisible();const saved=await page.evaluate(key=>JSON.parse(localStorage.getItem(key)),key);expect(saved.destinationAction.type).toBe('legacy-tomb');expect(saved.battle).toBeNull();expect(errors).toEqual([]);
});
