import { createHash } from 'node:crypto';
import { readFile, readdir, writeFile } from 'node:fs/promises';
import { dirname, join, relative, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const SCRIPT = fileURLToPath(import.meta.url);
const ROOT = resolve(dirname(SCRIPT), '..');
const CORE = [
  './',
  './index.html',
  './src/style.css',
  './src/campaign.css',
  './src/battle.css',
  './src/campaign-ui.js',
  './src/battle-view.js',
  './src/battle-terrain.js',
  './src/audio.js',
  './src/app.js',
  './src/item-details.js',
  './src/engine.js',
  './src/additional-items.js',
  './src/mounts.js',
  './src/northern-items.js',
  './src/fantasy-items.js',
  './src/fantasy-art.js',
  './src/armor-attachments.js',
  './src/enemy-progression.js',
  './src/enemy-rosters.js',
  './src/perks.js',
  './src/recruits.js',
  './src/town-events.js',
  './src/caravans.js',
  './src/map.js',
  './src/portraits.js',
  './manifest.webmanifest',
  './assets/icon.svg',
];

async function assetFiles(directory) {
  const entries = await readdir(directory, { withFileTypes: true });
  const nested = await Promise.all(entries.map(async entry => {
    const path = join(directory, entry.name);
    if (entry.isDirectory()) return assetFiles(path);
    if (entry.isFile() && /\.(png|jpg|mp3)$/i.test(entry.name) && !/^contact[-_]sheet/i.test(entry.name)) return [path];
    return [];
  }));
  return nested.flat();
}

export async function listOfflineAssets() {
  const assets = (await assetFiles(join(ROOT, 'assets')))
    .map(path => './' + relative(ROOT, path).split(sep).join('/'))
    .sort();
  return [...CORE, ...assets];
}

export async function renderServiceWorker() {
  const assets = await listOfflineAssets();
  const hash = createHash('sha256');
  hash.update(await readFile(SCRIPT));
  for (const asset of assets) {
    hash.update(asset).update('\0');
    hash.update(await readFile(join(ROOT, asset === './' ? 'index.html' : asset.slice(2)))).update('\0');
  }
  const cache = 'ashen-company-' + hash.digest('hex').slice(0, 16);
  return `// Generated by tools/build-cache.mjs. Do not edit by hand.
const CACHE = ${JSON.stringify(cache)};
const ASSETS = ${JSON.stringify(assets, null, 2)};
const urls = ASSETS.map(path => new URL(path, self.registration.scope).href);

self.addEventListener('install', event => event.waitUntil((async () => {
  const cache = await caches.open(CACHE);
  try {
    await cache.addAll(urls.map(url => new Request(url, { cache: 'reload' })));
    const present = await Promise.all(urls.map(url => cache.match(url)));
    if (!present.every(Boolean)) throw new Error('Offline cache is incomplete.');
    await self.skipWaiting();
  } catch (error) {
    await caches.delete(CACHE);
    throw error;
  }
})()));

self.addEventListener('activate', event => event.waitUntil((async () => {
  const cache = await caches.open(CACHE);
  const present = await Promise.all(urls.map(url => cache.match(url)));
  if (!present.every(Boolean)) throw new Error('Offline cache is incomplete.');
  const keys = await caches.keys();
  await Promise.all(keys.filter(key => key.startsWith('ashen-company-') && key !== CACHE).map(key => caches.delete(key)));
  await self.clients.claim();
})()));

function parseAudioRange(range, size) {
  const match = /^bytes=(\\d*)-(\\d*)$/i.exec(range.trim());
  if (!match || (!match[1] && !match[2]) || size <= 0) return null;
  let start;
  let end;
  if (!match[1]) {
    const suffixLength = Number(match[2]);
    if (!Number.isSafeInteger(suffixLength) || suffixLength <= 0) return null;
    start = Math.max(0, size - suffixLength);
    end = size - 1;
  } else {
    start = Number(match[1]);
    end = match[2] ? Number(match[2]) : size - 1;
    if (!Number.isSafeInteger(start) || !Number.isSafeInteger(end) || start > end || start >= size) return null;
    end = Math.min(end, size - 1);
  }
  return { start, end };
}

async function cachedAudioRange(cached, range) {
  const bytes = await cached.arrayBuffer();
  const size = bytes.byteLength;
  const selected = parseAudioRange(range, size);
  const headers = new Headers(cached.headers);
  headers.set('Accept-Ranges', 'bytes');
  if (!headers.has('Content-Type')) headers.set('Content-Type', 'audio/mpeg');
  if (!selected) {
    headers.set('Content-Range', 'bytes */' + size);
    headers.set('Content-Length', '0');
    return new Response(null, { status: 416, headers });
  }
  const length = selected.end - selected.start + 1;
  headers.set('Content-Range', 'bytes ' + selected.start + '-' + selected.end + '/' + size);
  headers.set('Content-Length', String(length));
  return new Response(bytes.slice(selected.start, selected.end + 1), { status: 206, headers });
}

self.addEventListener('fetch', event => {
  if (event.request.method !== 'GET' || !event.request.url.startsWith(self.registration.scope)) return;
  event.respondWith((async () => {
    const cache = await caches.open(CACHE);
    const cached = await cache.match(event.request, { ignoreSearch: true });
    if (cached) {
      const range = event.request.headers.get('Range');
      const isAudio = new URL(event.request.url).pathname.toLowerCase().endsWith('.mp3');
      return range && isAudio ? cachedAudioRange(cached, range) : cached;
    }
    if (event.request.mode === 'navigate') {
      return await cache.match(new URL('./index.html', self.registration.scope).href) || Response.error();
    }
    return Response.error();
  })());
});

self.addEventListener('message', event => {
  if (event.data?.type !== 'CHECK_OFFLINE') return;
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    const present = await Promise.all(urls.map(url => cache.match(url)));
    event.ports[0]?.postMessage({
      ready: present.every(Boolean),
      count: present.filter(Boolean).length,
      expected: urls.length,
      cache: CACHE,
    });
  })());
});
`;
}

export async function buildCache() {
  const source = await renderServiceWorker();
  await writeFile(join(ROOT, 'sw.js'), source, 'utf8');
  return source;
}

if (process.argv[1] && resolve(process.argv[1]) === SCRIPT) {
  await buildCache();
}
