import {ITEMS,GOODS,SETTLEMENTS,createGame,travelTo,tick,townAt,acceptContract,buyItem,sellItem,equipItem,unequipItem,recruit,camp,forage,getEquipment,terrainAt,validateSave,getMarket,buyFood,buyGood,sellGood,getContractOffers,getCompanyStats,getCampSites,startBattle,advanceBattle,resolveBattle,retreatBattle,finishBattle,trainAttribute,buySupplies} from './engine.js';
import {portraitSVG,itemImage} from './portraits.js';
import {mapHTML,mountMap,updateMap,focusMap,zoomMap,selectMapTown,selectMapCamp} from './map.js';
import {battleHTML} from './battle-view.js';
import {resourceHTML,companySheetHTML,campSidebarHTML,huntContractHTML,contractOffersHTML,battleResultsHTML,gameOverHTML,difficultyHTML} from './campaign-ui.js';
const SAVE_KEY='ashen-company-save-v1',$=s=>document.querySelector(s);
const esc=t=>String(t).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const item=id=>ITEMS.find(i=>i.id===id),town=id=>SETTLEMENTS.find(t=>t.id===id),good=id=>GOODS.find(g=>g.id===id);
const specialties={oakwatch:'Timber & grain',greyhaven:'Wool market',ironford:'Iron & affordable steel',thornwall:'High demand for supplies',redmere:'Salt trade',highpass:'Mountain trading post',saltwick:'Cheap salt',barrowfield:'Grain & wool'};
const townArt={oakwatch:'houses_02_01',greyhaven:'townhall_02',ironford:'stronghold_01',thornwall:'stronghold_02',redmere:'townhall_01',highpass:'fortified_outpost_01',saltwick:'houses_01_01',barrowfield:'houses_03_01'};
let chosenCamp=null,battleSpeed=0,battleElapsed=0;
let state=createGame(7391),tab='world',selected='captain',chosenTown='oakwatch',speed=0,slotFilter='all',marketTab='gear',toastTimer,saveProblem=false,corruptSave=null,unreadSave=false,saveError="";
try{const raw=localStorage.getItem(SAVE_KEY);if(raw){try{state=validateSave(JSON.parse(raw));chosenTown=townAt(state)?.id||'oakwatch';}catch(error){unreadSave=true;corruptSave=raw;saveError=error.message;}}}catch{saveProblem=true;}
if(state.battle)tab='battle';
function save(){if(unreadSave)return;try{localStorage.setItem(SAVE_KEY,JSON.stringify(state));saveProblem=false;}catch{if(!saveProblem)toast('Autosave unavailable. Export a save before closing.');saveProblem=true;}}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),4000);}
function person(){return state.party.find(p=>p.id===selected)||state.party[0];}
function icon(i,extra=''){return `<img class="equipment-icon ${extra}" src="${itemImage(i)}" alt="${esc(i.name)}" loading="lazy">`;}
function resources(){$('#resources').innerHTML=resourceHTML(state,speed);}
function run(action,...args){const result=action(state,...args);toast(result.message);save();render();return result;}
function showModal(title,body,kicker='ASHEN COMPANY'){speed=0;battleSpeed=0;updateSpeed();resources();$('#modal-content').innerHTML=`<div class="modal-header"><div><div class="eyebrow">${kicker}</div><h2>${title}</h2></div><button class="close-button" data-action="close-modal" aria-label="Close dialog">Close</button></div><div class="modal-body">${body}</div>`;if(!$('#modal').open)$('#modal').showModal();}
function contractHTML(){
 if(state.contract?.type==='hunt')return huntContractHTML(state,state.contract);
 if(!state.contract)return `<div class="contract-card"><h3>Find your next contract</h3><p>Earn crowns delivering goods or driving brigands from their camps.</p><button class="primary" data-action="contracts">View the notice board</button></div>`;
 const c=state.contract,t=town(c.to),supply=c.type==='supply';return `<div class="contract-card"><div class="eyebrow">${supply?'Supply contract':'Sealed dispatches'}</div><h3>${supply?`${c.quantity} ${good(c.goodId).name}`:'Delivery'} to ${t.name}</h3><p>${supply?`Cargo: ${state.cargo[c.goodId]||0} / ${c.quantity}. Buy goods at a market, then deliver.`:'Your dispatches are packed. Reach the destination to collect payment.'}</p><div class="contract-reward">${c.reward} crowns · ${c.renown||1} renown</div><button class="primary" data-travel="${t.id}">Travel to ${t.name}</button></div>`;
}
function sidebarHTML(){
 if(chosenCamp){const site=getCampSites(state).find(c=>c.id===chosenCamp);if(site)return campSidebarHTML(state,site)+contractHTML();}
 const t=town(chosenTown)||townAt(state)||SETTLEMENTS[0],here=townAt(state)?.id===t.id;
 const distance=Math.round(Math.hypot(t.x-state.position.x,t.y-state.position.y)/55*10)/10;
 return `<div class="location-header"><div class="eyebrow">${here?'Current settlement':'Selected destination'}</div><h2>${t.name}</h2><img class="settlement-portrait" src="./assets/world/${townArt[t.id]}.png" alt="${t.name}"><p class="town-specialty">${specialties[t.id]}</p></div><label class="destination-label" for="destinations">Destinations</label><select id="destinations">${SETTLEMENTS.map(s=>`<option value="${s.id}" ${s.id===t.id?'selected':''}>${s.name}${townAt(state)?.id===s.id?' (here)':''}</option>`).join('')}<optgroup label="Hostile locations">${getCampSites(state).map(c=>`<option value="camp:${c.id}">${c.name}${c.cleared?" (cleared)":""}</option>`).join('')}</optgroup></select><div class="stack sidebar-actions">${here?`<button class="primary" data-action="town">Enter settlement</button><button data-action="market">Marketplace</button><button data-action="contracts">Contracts</button><button data-action="recruit">Hire brothers</button>`:`<p class="travel-estimate">About ${distance} hours · terrain may slow travel</p><button class="primary" data-travel="${t.id}">Travel here</button>`}<div class="two-buttons"><button data-action="camp">Camp · 6h</button><button data-action="forage">Forage · 4h</button></div></div>${contractHTML()}<div class="upkeep">Daily upkeep: ${state.party.reduce((n,p)=>n+(getCompanyStats(p).dailyWage||5),0)} crowns + ${state.party.length} food</div>`;
}
function stripHTML(){return `<section class="company-strip" aria-label="Your company"><div class="strip-intro"><h3>Your company</h3><p>${state.party.length} / 12 brothers</p></div><div class="strip-roster">${state.party.map(p=>`<button class="mini-person ${tab==='company'&&p.id===selected?'active':''}" data-person="${p.id}" aria-label="Equip ${esc(p.name)}">${portraitSVG(p,getEquipment(p),80)}<span class="mini-name">${esc(p.name.split(' ')[0])}</span><span class="hp-bar"><span style="width:${Math.max(0,p.hp/getCompanyStats(p).maxHp*100)}%"></span></span></button>`).join('')}<button class="strip-recruit" data-action="recruit" aria-label="Recruit a companion">+</button></div><button class="secondary small" data-tab="company">Equipment</button></section>`;}
function worldHTML(){return `<section class="world-layout"><div class="map-wrap">${mapHTML()}<div class="map-caption"><span>The Grey Marches</span><small>Drag to pan · tap a settlement or hostile camp</small></div><div class="map-zoom"><button data-action="zoom-in" aria-label="Zoom in">+</button><button data-action="zoom-out" aria-label="Zoom out">−</button><button data-action="center" aria-label="Center on company">Company</button></div><div class="map-controls"><button data-speed="0" aria-label="Pause travel">Pause</button><button data-speed="1" aria-label="Normal travel speed">1×</button><button data-speed="3" aria-label="Fast travel speed">3×</button><span id="march-status">${state.destination?'On the march':'Company at rest'}</span></div></div><aside class="world-sidebar">${sidebarHTML()}</aside></section>${stripHTML()}`;}
function inventoryHTML(){
 const counts=new Map();state.inventory.forEach(id=>counts.set(id,(counts.get(id)||0)+1));
 const owned=[...counts].filter(([id])=>slotFilter==='all'||item(id).slot===slotFilter);
 return owned.map(([id,count])=>{const i=item(id),condition=state.inventoryCondition?.[state.inventory.indexOf(id)],armor=i.slot==='armor'||i.slot==='helmet';return `<button class="inventory-item" data-equip="${id}">${icon(i)}<strong>${i.name}${count>1?` ×${count}`:''}</strong><span>${armor?`${condition??i.armor} / ${i.armor} durability`:itemStatText(i)}</span><small>Tap to equip</small></button>`;}).join('')||'<p class="empty-state">No spare items in this slot. Buy gear at a settlement, or select another slot.</p>';
}
function companyHTML(){const p=person();if(!p)return gameOverHTML(state);selected=p.id;return companySheetHTML(state,p,slotFilter,inventoryHTML())+stripHTML();}
function journalHTML(){return `<section class="page"><div class="page-heading"><div><div class="eyebrow">DAY ${state.day}</div><h1>The company chronicle</h1></div><button data-tab="world">Return to the map</button></div><div class="journal-layout"><div>${[...state.log].reverse().map(s=>`<div class="journal-entry">${esc(s)}</div>`).join('')}</div><aside class="paper-card"><h2>A living on the road</h2><ol><li>Take a courier job for a guaranteed payment.</li><li>Buy local goods cheaply and sell where demand is high.</li><li>Supply orders need purchased cargo; check the required quantity.</li><li>Buy food before leaving. Each person eats once per day.</li><li>Equip your companions by tapping their portraits.</li></ol><h3>Trade routes</h3><p>Oakwatch timber sells well at Highpass. Saltwick salt is prized at Thornwall. Ironford has cheaper iron and equipment.</p><h3>Life as a mercenary</h3><p>Accept a brigand contract, approach the marked camp, and engage. Battles play automatically. Armor protects head and body separately; fatigue and morale affect the fighting. Afterward, collect loot, rest with tools and medicine, and return for payment.</p><p>Brothers gain experience. Spend their attribute increases in the company screen. Fallen brothers stay dead.</p><button data-action="settings">Save & offline settings</button></aside></div></section>`;}
function render(){
 resources();
 if(state.battle)tab='battle';
 $('#main').innerHTML=state.battle?(state.battle.status==='active'?battleHTML(state.battle,battleSpeed):battleResultsHTML(state)):state.gameOver?gameOverHTML(state):tab==='world'?worldHTML():tab==='company'?companyHTML():tab==='town'?townHTML():journalHTML();
 document.querySelectorAll('.nav-tabs [data-tab]').forEach(b=>{b.classList.toggle('active',b.dataset.tab===tab);b.disabled=!!state.battle;});
 if(tab==='world'&&!state.battle&&!state.gameOver){mountMap(state,chooseTown,startTravel,chooseCamp);if(chosenCamp)selectMapCamp(chosenCamp);else selectMapTown(town(chosenTown));}updateSpeed();
}
function chooseTown(t){chosenCamp=null;chosenTown=t.id;selectMapTown(t);const side=$('.world-sidebar');if(side)side.innerHTML=sidebarHTML();}
function chooseCamp(site){chosenCamp=site.id;selectMapCamp(site.id);const side=$('.world-sidebar');if(side)side.innerHTML=sidebarHTML();}
function townHTML(){const t=townAt(state);if(!t){tab='world';return worldHTML();}return `<section class="page settlement-page"><div class="page-heading"><div><div class="eyebrow">${t.kind} · ${specialties[t.id]}</div><h1>${t.name}</h1><p>${t.description}</p></div><button data-tab="world">Leave settlement</button></div><div class="settlement-scene"><img class="settlement-trees trees-left" src="./assets/world/world_detail_forest_green_01.png" alt=""><img class="settlement-building" src="./assets/world/${townArt[t.id]}.png" alt="${t.name}"><img class="settlement-trees trees-right" src="./assets/world/world_detail_autumn_green_01.png" alt=""></div><div class="settlement-services"><button data-action="market"><strong>Marketplace</strong><span>Equipment, trade goods and supplies</span></button><button data-action="recruit"><strong>Hiring</strong><span>Find brothers to fight under your banner</span></button><button data-action="contracts"><strong>Contracts</strong><span>Work for the local settlement</span></button></div><div class="town-footer">${contractHTML()}<div><h3>The company camp</h3><p>Tools repair armor. Medicine helps the wounded recover. Keep food and wages ready for the road.</p><button data-action="camp">Make camp · 6 hours</button></div></div></section>`;}
function engage(siteId){const site=getCampSites(state).find(c=>c.id===siteId);if(!site)return;showModal(site.name,`<div class="encounter-summary"><img src="./assets/world/fortified_outpost_01.png" alt=""><div>${difficultyHTML(site.difficulty)}<h3>Brigands ahead</h3><p>${site.enemies?.length||site.enemyCount||'?'} enemies hold this location. Your ${state.party.length} brothers will fight automatically with their current equipment.</p></div></div><p>Check armor, hitpoints, and ammunition. Death is permanent. Retreat remains possible during the battle.</p><div class="button-row"><button class="primary" data-fight="${site.id}">To arms!</button><button data-action="close-modal">Leave them be</button></div>`,'ENCOUNTER');}
function beginBattle(siteId){const result=startBattle(state,siteId);toast(result.message);if(!result.ok)return;speed=0;battleSpeed=1;battleElapsed=0;tab='battle';$('#modal').close();save();render();}
function suppliesHTML(market){return '<div class="supply-shop">'+(market.supplies||[]).map(row=>`<article class="provision-card"><span class="supply-symbol supply-${row.kind}"></span><h3>${esc(row.name)}</h3><p>${row.owned} in company stores · ${row.stock} available</p><p>${row.kind==='tools'?'Repair damaged armor when resting.':row.kind==='medicine'?'Treat wounds and recover hitpoints in camp.':'Consumed when brothers fire ranged weapons.'}</p><button data-supply="${row.kind}" data-quantity="5" ${row.stock<5||state.gold<row.buyPrice*5?'disabled':''}>Buy 5 · ${row.buyPrice*5} crowns</button></article>`).join('')+'</div>';}
function gearMarketHTML(market){return `<div class="market-ledger"><section><div class="inventory-title"><h3>Company stash</h3><small>Sell spare equipment</small></div><div class="shop-stash">${market.equipment.filter(r=>r.owned).map(row=>{const i=item(row.itemId);return `<button class="shop-tile sell-tile" data-sell="${i.id}" title="Sell ${i.name}">${icon(i)}<strong>${i.name}</strong><small>${row.owned} in stash</small><span>Sell ${row.sellPrice}</span></button>`;}).join('')||'<p>No spare equipment.</p>'}</div><button class="primary" data-action="go-company">Equip your brothers</button></section><section><div class="inventory-title"><h3>Trader's inventory</h3><small>Prices in crowns</small></div><div class="trader-grid">${market.equipment.map(row=>{const i=item(row.itemId);return `<button class="shop-tile" data-buy="${i.id}" ${!row.stock||state.gold<row.buyPrice?'disabled':''} title="${esc(i.description)}"><span class="stock-count">${row.stock}</span>${icon(i)}<strong>${i.name}</strong><small>${itemStatText(i)}</small><span>Buy ${row.buyPrice}</span></button>`;}).join('')}</div></section></div>`;}
function itemStatText(i){return i.slot==='shield'?`+${i.defense||0} defense`:i.slot==='weapon'?`${i.damageMin||0}–${i.damageMax||0} damage`:`${i.armor} durability`;}
function updateSpeed(){document.querySelectorAll('[data-speed]').forEach(b=>b.classList.toggle('active',Number(b.dataset.speed)===speed));const s=$('#march-status');if(s)s.textContent=state.destination?(speed?'On the march':'Travel paused'):'Company at rest';}
function market(){const market=getMarket(state);if(!market){toast('Travel to a settlement to trade.');return;}const t=market.town;let content;
 if(marketTab==='gear')content=gearMarketHTML(market);
 else if(marketTab==='supplies')content=suppliesHTML(market);
 else if(marketTab==='trade')content=`<p class="market-tip">Buy at a producing settlement, sell where demand is high. Cargo ${Object.values(state.cargo).reduce((s,n)=>s+n,0)} / 30.</p><div class="goods-list">${market.goods.map(r=>`<article class="trade-row"><div><h3>${r.name}</h3><p>${r.description}</p><small>Stock: ${r.stock} · In cargo: ${r.owned}</small></div><div class="trade-actions"><button data-buy-good="${r.goodId}" ${r.stock===0||state.gold<r.buyPrice?'disabled':''}>Buy ${r.buyPrice}</button><button data-sell-good="${r.goodId}" ${!r.owned?'disabled':''}>Sell ${r.sellPrice}</button></div></article>`).join('')}</div><p class="market-tip">Good routes: Oakwatch timber → Highpass · Saltwick salt → Thornwall · Ironford iron → Saltwick.</p>`;
 else content=`<div class="provision-card"><h3>Food for the road</h3><p>${state.food} provisions in the company, enough for ${Math.floor(state.food/state.party.length)} days.<br>Daily consumption: ${state.party.length}. Merchant stock: ${market.food.stock}.</p><div class="button-row"><button class="primary" data-food="5" ${market.food.stock<5||state.gold<market.food.buyPrice*5?'disabled':''}>Buy 5 · ${market.food.buyPrice*5} crowns</button><button data-food="15" ${market.food.stock<15||state.gold<market.food.buyPrice*15?'disabled':''}>Buy 15 · ${market.food.buyPrice*15} crowns</button></div><p>Or forage for four hours to gather supplies without spending crowns.</p><button data-action="forage">Forage · 4 hours</button></div>`;
 showModal('Marketplace',`<div class="market-summary"><span>${specialties[t.id]}</span><strong>${state.gold} crowns</strong></div><div class="market-tabs">${[['gear','Weapons & armor'],['trade','Trade goods'],['food','Provisions'],['supplies','Supplies']].map(([id,label])=>`<button data-market-tab="${id}" class="${marketTab===id?'active':''}">${label}</button>`).join('')}</div>${content}`,t.name);
}
function contracts(){const t=townAt(state);if(!t){toast('Reach a settlement to find work.');return;}if(state.contract){showModal('Your current contract',contractHTML(),t.name);return;}showModal('Available contracts',contractOffersHTML(state,getContractOffers(state,t.id)),t.name);}
function recruitModal(){if(!townAt(state)){toast('Reach a settlement to hire companions.');return;}const preview=structuredClone(state),res=recruit(preview);if(!res.ok){toast(res.message);return;}const p=preview.party.at(-1),cost=state.gold-preview.gold;showModal('A new companion',`<div class="recruit-preview">${portraitSVG(p,getEquipment(p),190)}<div><div class="eyebrow">${esc(p.background)}</div><h2>${esc(p.name)}</h2><p>Hiring fee ${cost} crowns.<br>Daily upkeep: 5 crowns and 1 food.<br>Comes without equipment.</p></div></div><button class="primary" data-action="hire">Hire for ${cost} crowns</button>`);}
function settings(){showModal('Save & offline play',`<p>Your company is saved on this device. Export a backup before travelling.</p><div class="save-note">On iPad: open in Safari online, Share → Add to Home Screen, then launch the icon. Wait for <strong>Offline ready</strong>, and test an airplane-mode relaunch before your flight.</div><div class="button-row"><button class="primary" data-action="export">Export save</button><button data-action="import">Import save</button>${corruptSave!==null?'<button data-action="export-recovery">Export damaged save</button>':''}</div><input id="import-file" class="hidden" type="file" accept=".json,application/json"><p>${saveProblem?'Autosave unavailable. Export your progress.':unreadSave?'A save could not be loaded (${esc(saveError)}). The original is preserved for export.':'Autosave active. Saves do not sync between devices.'}</p><div class="divider"></div><div class="button-row"><button class="danger" data-action="new-game">Start a new company</button></div><p class="credits">Artwork: Battle Brothers / Legends contributors. Personal noncommercial prototype. <a href="https://github.com/karmiphuc/ashen-company/blob/main/docs/ASSET-CREDITS.md" target="_blank" rel="noopener">Asset credits</a>.<br>Version 0.3 · Contracts, automated battles, loot and company progression.</p>`);}
function exportSave(recovery=false){const text=recovery&&corruptSave!==null?corruptSave:JSON.stringify(state,null,2);const url=URL.createObjectURL(new Blob([text],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=recovery?'ashen-company-damaged-save.json':`ashen-company-day-${state.day}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);toast('Save exported. Keep the file as a backup.');}
function startTravel(x,y){const r=travelTo(state,x,y);toast(r.message);if(r.ok){speed=1;tab='world';$('#modal').close();save();render();}}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;
 if(b.dataset.battleSpeed!==undefined){battleSpeed=Number(b.dataset.battleSpeed);battleElapsed=0;render();return;}
 if(b.dataset.fight){beginBattle(b.dataset.fight);return;}
 if(b.dataset.engage){engage(b.dataset.engage);return;}
 if(b.dataset.selectCamp){const site=getCampSites(state).find(c=>c.id===b.dataset.selectCamp);if(site){chosenCamp=site.id;tab='world';$('#modal').close();render();focusMap(site);}return;}
 if(b.dataset.campTravel){const site=getCampSites(state).find(c=>c.id===b.dataset.campTravel);if(site){chosenCamp=site.id;startTravel(site.x,site.y);}return;}
 if(b.dataset.train){run(trainAttribute,selected,b.dataset.train);return;}
 if(b.dataset.supply){run(buySupplies,b.dataset.supply,Number(b.dataset.quantity)||5);market();return;}
 if(b.dataset.tab){if(state.battle)return;tab=b.dataset.tab;speed=0;render();return;}
 if(b.dataset.person){selected=b.dataset.person;tab='company';speed=0;render();return;}
 if(b.dataset.slot){slotFilter=b.dataset.slot;render();return;}
 if(b.dataset.speed!==undefined){speed=Number(b.dataset.speed);if(speed&&!state.destination){speed=0;toast('Select a settlement, then choose Travel here.');}updateSpeed();resources();return;}
 if(b.dataset.travel){const t=town(b.dataset.travel);chosenCamp=null;chosenTown=t.id;startTravel(t.x,t.y);return;}
 if(b.dataset.marketTab){marketTab=b.dataset.marketTab;market();return;}
 if(b.dataset.equip){run(equipItem,selected,b.dataset.equip);return;}
 if(b.dataset.unequip){run(unequipItem,selected,b.dataset.unequip);return;}
 if(b.dataset.buy){run(buyItem,b.dataset.buy);market();return;}
 if(b.dataset.sell){run(sellItem,b.dataset.sell);market();return;}
 if(b.dataset.food){run(buyFood,Number(b.dataset.food));market();return;}
 if(b.dataset.buyGood){run(buyGood,b.dataset.buyGood);market();return;}
 if(b.dataset.sellGood){run(sellGood,b.dataset.sellGood);market();return;}
 if(b.dataset.accept){run(acceptContract,b.dataset.origin,b.dataset.accept);$('#modal').close();return;}
 switch(b.dataset.action){
 case 'town':tab='town';speed=0;render();break;
 case 'company':tab='company';speed=0;render();break;
 case 'nearest-town':chosenCamp=null;chosenTown=[...SETTLEMENTS].sort((a,b)=>Math.hypot(a.x-state.position.x,a.y-state.position.y)-Math.hypot(b.x-state.position.x,b.y-state.position.y))[0].id;render();break;
 case 'resolve-battle':battleSpeed=0;run(resolveBattle);break;
 case 'retreat-battle':battleSpeed=0;showModal('Retreat from battle?', '<p>Your company will attempt to disengage. Wounds and armor damage remain; retreating can cost lives.</p><div class="button-row"><button class="danger" data-action="confirm-retreat">Retreat now</button><button data-action="close-modal">Keep fighting</button></div>');break;
 case 'confirm-retreat':run(retreatBattle);$('#modal').close();break;
 case 'finish-battle':{const siteId=state.battle?.campId;const r=finishBattle(state);toast(r.message);if(r.ok){chosenCamp=siteId;tab='world';selected=state.party[0]?.id||'';save();render();}break;}
 case 'close-modal':$('#modal').close();if(state.battle)render();break;case 'market':market();break;case 'contracts':contracts();break;case 'recruit':recruitModal();break;
 case 'hire':run(recruit);$('#modal').close();break;case 'camp':speed=0;run(camp);break;case 'forage':speed=0;run(forage);if($('#modal').open)market();break;
 case 'go-company':$('#modal').close();tab='company';slotFilter='all';render();break;case 'settings':settings();break;
 case 'center':focusMap(state.position);break;case 'zoom-in':zoomMap(1.25);break;case 'zoom-out':zoomMap(.8);break;
 case 'export':exportSave();break;case 'export-recovery':exportSave(true);break;case 'import':$('#import-file').click();break;
 case 'new-game':showModal('Replace your company?',`<p>This replaces the save on this device. Export a backup first to keep the current company.</p><div class="button-row"><button data-action="export">Export current save</button><button class="danger" data-action="confirm-new">Replace company</button><button data-action="close-modal">Keep playing</button></div>`);break;
 case 'confirm-new':state=createGame();chosenCamp=null;battleSpeed=0;selected=state.party[0].id;chosenTown='oakwatch';unreadSave=false;corruptSave=null;save();tab='world';$('#modal').close();render();toast('Your new company gathers at Oakwatch.');break;
 }
});
document.addEventListener('change',async e=>{if(e.target.id==='destinations'){const value=e.target.value;if(value.startsWith('camp:')){const site=getCampSites(state).find(c=>c.id===value.slice(5));chooseCamp(site);focusMap(site);}else{chooseTown(town(value));focusMap(town(value));}return;}if(e.target.id!=='import-file')return;const file=e.target.files[0];if(!file)return;try{if(file.size>250000)throw new Error('Save file is too large.');state=validateSave(JSON.parse(await file.text()));unreadSave=false;selected=state.party[0]?.id||'';chosenTown=townAt(state)?.id||'oakwatch';chosenCamp=null;battleSpeed=0;tab=state.battle?'battle':'world';speed=0;save();$('#modal').close();render();toast('Company restored from your save.');}catch(error){toast(`Could not import save: ${error.message}`);}});
$('#settings-button').addEventListener('click',settings);
document.addEventListener('visibilitychange',()=>{if(document.hidden){speed=0;battleSpeed=0;save();if(state.battle)render();else updateSpeed();}});window.addEventListener('pagehide',save);
document.addEventListener('keydown',e=>{if(e.code==='Space'&&!$('#modal').open&&!['INPUT','SELECT','BUTTON'].includes(e.target.tagName)){e.preventDefault();speed=state.destination?(speed?0:1):0;updateSpeed();resources();}});
let last=performance.now(),lastSave=0,lastHour='';
function animate(now){
 const elapsed=Math.min((now-last)/1000,.25);last=now;
 if(!document.hidden&&!$('#modal').open){
  if(state.battle?.status==='active'&&battleSpeed){battleElapsed+=elapsed*battleSpeed;if(battleElapsed>=.65){battleElapsed=0;advanceBattle(state);if(state.battle.status!=='active')battleSpeed=0;save();render();}}
  else if(!state.battle&&speed&&state.destination&&tab==='world'){
   const before=state.contract;tick(state,elapsed*speed*.42);updateMap(state);const key=`${state.day}-${Math.floor(state.hour)}`;if(key!==lastHour){resources();lastHour=key;}
   if(!state.destination){speed=0;chosenTown=townAt(state)?.id||chosenTown;save();render();toast(before&&!state.contract?'Contract fulfilled. Payment received.':chosenCamp?'The company reaches the hostile location. Inspect the enemy before engaging.':'The company has arrived.');}
   if(now-lastSave>2000){save();lastSave=now;}
  }
 }
 requestAnimationFrame(animate);
}
render();requestAnimationFrame(animate);if(unreadSave)toast('A damaged save was preserved. Open Save / Menu to recover.');else save();
async function prepareOffline(){const label=$('#offline-status');if(!('serviceWorker'in navigator)){label.textContent='Offline unavailable';return;}try{await navigator.serviceWorker.register('./sw.js');const reg=await navigator.serviceWorker.ready;const check=()=>{const ch=new MessageChannel();ch.port1.onmessage=e=>{label.textContent=e.data?.ready?'Offline ready':'Downloading offline files…';label.classList.toggle('ready',!!e.data?.ready);};(navigator.serviceWorker.controller||reg.active)?.postMessage({type:'CHECK_OFFLINE'},[ch.port2]);};check();navigator.serviceWorker.addEventListener('controllerchange',check);}catch{label.textContent='Open online to prepare';}}
prepareOffline();
