import {getLegendaryBlacksmith,getBlacksmithQuestEncounters,getItem,getReforgeQuote,shieldMaximum,getStashCapacity,townAt} from './engine.js';
import {forgeProfileRows,forgeAffixName,isNamedItem,isForgeSlot} from './reforged-items.js';
import {itemImage} from './portraits.js';
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function forgeSlotsHTML(a){
 if(!a)return '';
 if(a.locked)return '<span class="forge-legacy" title="Original bonuses remain intact. Further merges are locked; full transfers keep this restriction.">◆ Legacy · merge locked</span>';
 return `<div class="forge-affix-slots">${['prefix','suffix'].map(kind=>`<div class="forge-slot-row"><small>${kind==='prefix'?'✦ Prefix':'◇ Suffix'} ${a[`${kind}es`].length}/2${a[`${kind}es`].length===2?' · Full':''}</small>${Array.from({length:2},(_,i)=>{const affix=a[`${kind}es`][i];return `<span class="forge-slot${affix?' filled':''}" title="${esc(affix?forgeProfileRows(affix.profile,{}).map(r=>r.value).join('; '):'Available affix slot')}">${affix?esc(forgeAffixName(kind,affix)):'＋'}</span>`;}).join('')}</div>`).join('')}</div>`;
}
export function forgeMaterialsHTML(quote){
 if(!Object.keys(quote.materials).length)return '<small class="forge-free">First reforge: gold and materials waived</small>';
 const goods={iron:['▰','Iron'],wool:['♧','Wool'],timber:['▥','Timber']};
 return `<div class="forge-recipe" aria-label="Required cargo materials">${Object.entries(quote.materials).map(([id,n])=>{const [icon,name]=goods[id],owned=quote.ownedMaterials[id]??0;return `<span class="forge-material${owned<n?' missing':''}" title="${name}: need ${n}, carrying ${owned}" aria-label="${name}: need ${n}, carrying ${owned}"><span aria-hidden="true">${icon}</span> ${name} ${owned}/${n}</span>`;}).join('')}</div>`;
}
const art='<img class="forge-art" src="./assets/world/legendary-blacksmith.png" alt="Odran’s workshop and forge">';
function summary(item,condition){return item.slot==='weapon'?`${item.damageMin}–${item.damageMax} damage · ${item.fatigue??0} fatigue`:item.slot==='shield'?`${condition} / ${shieldMaximum(item.id)} durability · ${item.defense} defense`:`${condition} / ${item.armor} armor · ${item.fatigue??0} fatigue`;}
export function blacksmithSummonsHTML(state){const b=getLegendaryBlacksmith(state);return `<section class="forge-summons">${art}<div><h3>The Rekindled Forge</h3><p>Your named collection has reached <strong>Odran, the Last Ember</strong>. Visit <strong>Ironford → Legendary Blacksmith</strong> to accept <strong>Cold Hearth</strong>.</p><p>Bring <strong>8 Iron, 6 Timber and 10 Tools</strong>. Four side quests restore the forge, unlocking named-item merges and full transfers.</p>${!b.access.servicesAvailable?'<p class="forge-warning">Ironford is blocked by the crisis. Liberate it to visit Odran; your summons and quest remain available.</p>':''}<div class="button-row">${b.access.servicesAvailable&&townAt(state)?.id==='ironford'?'<button class="primary" data-action="blacksmith-speak">Speak to Odran</button>':''}<button data-action="blacksmith-map">Show Ironford on map</button><button data-action="blacksmith-journal">View side quest</button><button data-action="blacksmith-later">Later</button></div></div></section>`;}
export function blacksmithJournalHTML(state){const b=getLegendaryBlacksmith(state);if(!b.discovered)return '';const site=getBlacksmithQuestEncounters(state)[0];return `<section id="blacksmith-side-quest" class="paper-card forge-journal"><div class="eyebrow">SIDE QUEST · ${b.unlocked?'COMPLETED':`${b.stage} / 4`}</div><h2>${b.unlocked?'The Rekindled Forge':esc(b.quest.name)}</h2><p>${b.unlocked?'Odran’s named merging and full transfers are available in Ironford.':esc(b.quest.objective)}</p>${b.stage===1?`<p class="forge-materials">Iron ${b.materials.iron}/8 · Timber ${b.materials.timber}/6 · Tools ${b.materials.tools}/10</p>`:''}<div class="button-row"><button data-action="legendary-blacksmith">${b.unlocked?'View forge':'Quest guidance'}</button><button data-action="blacksmith-map">Show Ironford</button>${site?`<button data-blacksmith-site="${esc(site.id)}">Show quest site</button>`:''}</div></section>`;}
export function blacksmithPanelHTML(state,selection={}){
 const b=getLegendaryBlacksmith(state);
 if(!b.discovered)return '<p>Odran has not sent his summons yet. Own five named/famed items; discovery checks daily.</p>';
 if(!b.unlocked){const q=b.quest,site=getBlacksmithQuestEncounters(state)[0],atForge=!state.destination&&townAt(state)?.id==='ironford'&&b.access.servicesAvailable;
 return `<section class="forge-quest">${art}<div class="eyebrow">THE REKINDLED FORGE · ${b.stage} / 4</div><h3>${esc(q.name)}</h3><p>${esc(q.objective)}</p>${b.stage===1?`<div class="forge-materials"><span>Iron <strong>${b.materials.iron}/8</strong></span><span>Timber <strong>${b.materials.timber}/6</strong></span><span>Tools <strong>${b.materials.tools}/10</strong></span></div>${state.contract?'<small>These materials may also be needed for your ordinary contract.</small>':''}`:''}<p>${b.stage===4?'Reward: permanent forge access, one free reforge and a named sword.':`Reward: ${q.reward} crowns · next quest`}</p>${!b.access.servicesAvailable?'<p class="forge-warning">Liberate Ironford to restore access. Quest progress is preserved.</p>':!atForge?'<p>Visit Odran in Ironford to accept or turn in this quest.</p>':''}<div class="button-row">${q.status==='offered'?`<button class="primary" data-blacksmith-accept="${b.stage}" ${atForge?'':'disabled'}>Accept quest</button>`:`<button class="primary${q.ready?' is-ready':''}" data-blacksmith-turnin="${b.stage}" ${atForge&&q.ready?'':'disabled'}>${b.stage===1?'Deliver materials':'Return quest object'}</button>`}${site?`<button data-blacksmith-site="${esc(site.id)}">Show quest site</button><button data-blacksmith-march="${esc(site.id)}">March to objective</button>`:''}<button data-action="blacksmith-map">Show Ironford</button></div></section>`;}
 const donorIndex=selection.donor,recipientIndex=selection.recipient,donor=getItem(state.inventory[donorIndex]),recipient=getItem(state.inventory[recipientIndex]);
 const mode=isNamedItem(recipient)?'merge':'transfer',quote=donor&&recipient?getReforgeQuote(state,donorIndex,recipientIndex,mode):null;
 const filter=selection.filter??'all',search=(selection.search??'').toLowerCase();
 const candidates=state.inventory.map((id,index)=>({item:getItem(id),index,condition:state.inventoryCondition[index]})).filter(row=>isForgeSlot(row.item.slot)&&(filter==='all'||row.item.slot===filter)&&row.item.name.toLowerCase().includes(search));
 const cards=(side)=>candidates.filter(row=>side==='donor'?isNamedItem(row.item):!donor||row.item.slot===donor.slot).map(({item,index,condition})=>`<button class="forge-item${selection[side]===index?' selected':''}" data-forge-select="${side}" data-forge-index="${index}" aria-pressed="${selection[side]===index}" ${side==='recipient'&&index===donorIndex?'disabled':''}><img src="${itemImage(item)}" alt=""><span><strong>${esc(item.name)}</strong><small>Copy ${index+1} · ${esc(summary(item,condition))}</small><span class="forge-badge">${isNamedItem(item)?'Named':'Ordinary'}</span></span></button>`).join('')||`<p class="empty-state">${side==='donor'?'No matching named stash gear.':'No compatible recipient in the stash.'}</p>`;
 const selectedSummary=quote?.ok?`<div class="forge-result-art"><img src="${itemImage(recipient)}" alt=""><h4>${esc(recipient.name)}</h4></div><p class="forge-mode">${mode==='merge'?'Merge · 2 prefixes + 2 suffixes max':'Full transfer · preserves affix slots'}</p><p>${esc(quote.message)}</p>${forgeSlotsHTML(mode==='merge'?quote.recipientAffixes:quote.donorAffixes)}${mode==='transfer'?`<strong>${esc(summary(quote.result,quote.condition))}</strong>`:'<p>Original craftsmanship stays. Matching affixes only upgrade; others fill open slots. Eligible additions are revealed after forging.</p>'}<details><summary>${mode==='merge'?'Possible additions':'Transferred bonuses'}</summary><dl>${quote.possible.map(r=>`<div><dt>${esc(r.label)}</dt><dd>${esc(r.value)}${r.inactive?` · ${esc(r.inactive)}`:''}</dd></div>`).join('')}</dl></details>${mode==='transfer'&&quote.warnings.length?`<p class="forge-warning">${esc(quote.warnings.join('; '))}</p>`:''}${forgeMaterialsHTML(quote)}<p><strong>${quote.fee?`${quote.fee} crowns`:'Free first reforge'}</strong> · ${state.gold} available</p><p class="forge-warning">The donor is permanently destroyed. The recipient keeps its design, skills and existing wear.</p><button class="primary" data-action="forge-confirm" ${quote.affordable?'':'disabled'}>${mode==='merge'?'Destroy donor & merge':'Destroy donor & transfer'}</button>`:quote?`${forgeSlotsHTML(quote.recipientAffixes)}<p class="forge-warning">${esc(quote.message)}</p>${quote.blockedAffixes?`<details><summary>Why these affixes cannot merge</summary><dl>${quote.blockedAffixes.map(o=>`<div><dt>${esc(forgeAffixName(o.kind,o.affix))}</dt><dd>${esc(o.reason)}</dd></div>`).join('')}</dl></details>`:''}`:'<p>Select a named donor and a compatible recipient.</p>';
 return `<section class="forge-workbench"><header>${art}<div><h3>Named workmanship lives on</h3><p>Named → named: fill slots or upgrade a roll.<br>Named → ordinary: transfer the complete package.</p><small>Stash gear only. Body armor, helmets, shields and all weapon classes. First reforge free; then 1,000 crowns + cargo materials.</small></div></header>${!b.rewardClaimed?`<button data-action="blacksmith-reward">Claim Odran’s named sword${state.inventory.length>=getStashCapacity(state)?' · needs a free stash slot':''}</button>`:''}<div class="forge-filters"><label>Category<select data-forge-filter>${[['all','All gear'],['weapon','Weapons'],['armor','Body armor'],['helmet','Helmets'],['shield','Shields']].map(([value,label])=>`<option value="${value}" ${filter===value?'selected':''}>${label}</option>`).join('')}</select></label><label>Find gear<input data-forge-search value="${esc(selection.search??'')}" placeholder="Item name"></label></div><div class="forge-columns"><section><h4>1 · Sacrifice <small>Destroyed permanently</small></h4><div class="forge-items">${cards('donor')}</div></section><section><h4>2 · Recipient</h4><div class="forge-items">${cards('recipient')}</div></section><section class="forge-preview" aria-live="polite"><h4>3 · Result</h4>${selectedSummary}<details><summary>Limits and inactive bonuses</summary><p>Protection caps: body 650, head 500. Weapon damage 300; shield defense 80. Penetration and head chance cap at 100%. Maximum two prefixes and two suffixes. Duplicate affixes never add together; original named craftsmanship stays fixed. Materials prepare all eligible donor affixes, so costs stay the same regardless of the random result. Inactive affixes occupy slots. Legacy reforged gear retains its bonuses but cannot accumulate further merges. Ranged reach and throwing capacity stay inactive on unsuitable weapons. The full accumulated package can be sacrificed onward.</p></details></section></div></section>`;
}
export function forgeConfirmationHTML(quote){return `<section class="forge-confirmation"><h3>${quote.mode==='merge'?'Merge within affix slots':'Transfer the full named package'}</h3><p>Permanently destroy <strong>${esc(quote.donor.name)}</strong> (stash copy ${quote.donorIndex+1}) to reforge <strong>${esc(quote.recipient.name)}</strong> (copy ${quote.recipientIndex+1}).</p><p>${quote.mode==='merge'?'The recipient keeps its craftsmanship. Eligible affixes fill open slots or replace matching weaker rolls, up to two prefixes and two suffixes.':'The ordinary recipient inherits every donor bonus.'} Existing wear remains.</p>${forgeMaterialsHTML(quote)}<p><strong>${quote.fee?`${quote.fee} crowns`:'Free first reforge'}</strong></p><div class="button-row"><button class="danger" data-action="forge-commit">Destroy &amp; reforge</button><button data-action="legendary-blacksmith">Cancel</button></div></section>`;}
export function forgeSuccessHTML(state,result){const item=getItem(result.itemId);return `<section class="forge-success"><img src="${itemImage(item)}" alt=""><h3>${esc(item.name)}</h3><p>The reforged item is in your stash.</p>${forgeSlotsHTML(item.forgeAffixes)}<dl>${result.added.map(r=>`<div><dt>${esc(r.label)}</dt><dd>${esc(r.value)}</dd></div>`).join('')}</dl><div class="button-row"><button data-inspect="${esc(item.id)}" data-item-source="forge">Inspect result</button><button data-action="legendary-blacksmith">Reforge another</button><button data-action="close-modal">Close</button></div></section>`;}
