// Generated by tools/content/import-bb-shields.py.
export const DLC_SHIELDS = Object.freeze([
  {
    "id": "bb-auxiliary-shield",
    "name": "Ancient Auxiliary Shield",
    "slot": "shield",
    "visual": "bb-auxiliary-shield",
    "price": 40,
    "armor": 15,
    "defense": 15,
    "rangedDefense": 15,
    "durability": 16,
    "fatigue": 10,
    "collection": "base",
    "sourceKind": "ordinary",
    "sourceCulture": "ancient",
    "description": "A wooden light shield in oval shape. The wood seems brittle and old, making it less durable.",
    "role": "+15 melee defense, +15 ranged defense; 16 durability at a 10 fatigue cost."
  },
  {
    "id": "bb-coffin-shield",
    "name": "Ancient Coffin Shield",
    "slot": "shield",
    "visual": "bb-coffin-shield",
    "price": 40,
    "armor": 15,
    "defense": 15,
    "rangedDefense": 20,
    "durability": 20,
    "fatigue": 12,
    "collection": "base",
    "sourceKind": "ordinary",
    "sourceCulture": "ancient",
    "description": "An octagonal shield made of wood and reinforced with bronze. Time has taken its toll and the wood has become brittle.",
    "role": "+15 melee defense, +20 ranged defense; 20 durability at a 12 fatigue cost."
  },
  {
    "id": "bb-tower-shield",
    "name": "Ancient Tower Shield",
    "slot": "shield",
    "visual": "bb-tower-shield",
    "price": 70,
    "armor": 20,
    "defense": 20,
    "rangedDefense": 20,
    "durability": 24,
    "fatigue": 20,
    "collection": "base",
    "sourceKind": "ordinary",
    "sourceCulture": "ancient",
    "description": "A tall and heavy tower shield that offers good protection, but is very bulky to handle. It appears to be old and worn down.",
    "role": "+20 melee defense, +20 ranged defense; 24 durability at a 20 fatigue cost."
  },
  {
    "id": "bb-faction-heater-shield",
    "name": "Heraldic Heater Shield",
    "slot": "shield",
    "visual": "bb-faction-heater-shield",
    "price": 88,
    "armor": 20,
    "defense": 20,
    "rangedDefense": 15,
    "durability": 32,
    "fatigue": 14,
    "collection": "base",
    "sourceKind": "ordinary",
    "sourceCulture": "mercenary",
    "description": "A triangular wooden shield covered with leather and canvas.",
    "role": "+20 melee defense, +15 ranged defense; 32 durability at a 14 fatigue cost."
  },
  {
    "id": "bb-faction-kite-shield",
    "name": "Heraldic Kite Shield",
    "slot": "shield",
    "visual": "bb-faction-kite-shield",
    "price": 70,
    "armor": 15,
    "defense": 15,
    "rangedDefense": 25,
    "durability": 48,
    "fatigue": 16,
    "collection": "base",
    "sourceKind": "ordinary",
    "sourceCulture": "mercenary",
    "description": "An elongated wooden shield covered in leather that offers good protection also to the lower body. Somewhat bulky to handle in close combat engagements.",
    "role": "+15 melee defense, +25 ranged defense; 48 durability at a 16 fatigue cost."
  },
  {
    "id": "bb-faction-wooden-shield",
    "name": "Heraldic Wooden Shield",
    "slot": "shield",
    "visual": "bb-faction-wooden-shield",
    "price": 40,
    "armor": 15,
    "defense": 15,
    "rangedDefense": 15,
    "durability": 24,
    "fatigue": 10,
    "collection": "base",
    "sourceKind": "ordinary",
    "sourceCulture": "mercenary",
    "description": "A round wooden shield.",
    "role": "+15 melee defense, +15 ranged defense; 24 durability at a 10 fatigue cost."
  },
  {
    "id": "bb-gilders-embrace-shield",
    "name": "Gilder's Embrace",
    "slot": "shield",
    "visual": "bb-gilders-embrace-shield",
    "price": 14000,
    "armor": 25,
    "defense": 32,
    "rangedDefense": 25,
    "durability": 1226,
    "fatigue": 16,
    "collection": "beasts-and-exploration",
    "sourceKind": "legendary",
    "sourceCulture": "mercenary",
    "description": "A rare gilder's embrace with independently rolled Battle Brothers-style modifiers. An ornate metal shield with a bright gilded shine that reflects even the tiniest ray of light with the power of the sun itself. Adapted as equipment; source regeneration and magical effects are not simulated.",
    "role": "+32 melee defense, +25 ranged defense; 1226 durability at a 16 fatigue cost, with two permanent rolled bonuses.",
    "rarity": "named",
    "sourceNamedShield": true,
    "sourceStats": {
      "armor": 25,
      "defense": 25,
      "rangedDefense": 25,
      "durability": 786,
      "fatigue": 16
    },
    "baseId": "bb-gilders-embrace-shield",
    "rollVersion": 2,
    "rollModifiers": [
      "melee-defense",
      "durability"
    ],
    "bonuses": [
      {
        "label": "Melee defense",
        "value": "+7"
      },
      {
        "label": "Shield durability",
        "value": "+440"
      }
    ]
  },
  {
    "id": "bb-named-bandit-heater-shield",
    "name": "Bandit Heater Shield",
    "slot": "shield",
    "visual": "bb-named-bandit-heater-shield",
    "price": 500,
    "armor": 20,
    "defense": 20,
    "rangedDefense": 20,
    "durability": 49,
    "fatigue": 14,
    "collection": "base",
    "sourceKind": "named",
    "sourceCulture": "mercenary",
    "description": "A rare bandit heater shield with independently rolled Battle Brothers-style modifiers. A sturdy triangular shield well suited for close combat. This one is an exceptionally well-crafted and balanced exemplar.",
    "role": "+20 melee defense, +20 ranged defense; 49 durability at a 14 fatigue cost, with two permanent rolled bonuses.",
    "rarity": "named",
    "sourceNamedShield": true,
    "sourceStats": {
      "armor": 20,
      "defense": 20,
      "rangedDefense": 15,
      "durability": 32,
      "fatigue": 14
    },
    "baseId": "bb-named-bandit-heater-shield",
    "rollVersion": 2,
    "rollModifiers": [
      "durability",
      "ranged-defense"
    ],
    "bonuses": [
      {
        "label": "Shield durability",
        "value": "+17"
      },
      {
        "label": "Ranged defense",
        "value": "+5"
      }
    ]
  },
  {
    "id": "bb-named-bandit-kite-shield",
    "name": "Bandit Kite Shield",
    "slot": "shield",
    "visual": "bb-named-bandit-kite-shield",
    "price": 500,
    "armor": 15,
    "defense": 20,
    "rangedDefense": 32,
    "durability": 48,
    "fatigue": 16,
    "collection": "base",
    "sourceKind": "named",
    "sourceCulture": "mercenary",
    "description": "A rare bandit kite shield with independently rolled Battle Brothers-style modifiers. A long, wooden shield covering the whole body for good protection against ranged attacks. This particular shield shows some unique craftsmanship and is a rare find.",
    "role": "+20 melee defense, +32 ranged defense; 48 durability at a 16 fatigue cost, with two permanent rolled bonuses.",
    "rarity": "named",
    "sourceNamedShield": true,
    "sourceStats": {
      "armor": 15,
      "defense": 15,
      "rangedDefense": 25,
      "durability": 48,
      "fatigue": 16
    },
    "baseId": "bb-named-bandit-kite-shield",
    "rollVersion": 2,
    "rollModifiers": [
      "melee-defense",
      "ranged-defense"
    ],
    "bonuses": [
      {
        "label": "Melee defense",
        "value": "+5"
      },
      {
        "label": "Ranged defense",
        "value": "+7"
      }
    ]
  },
  {
    "id": "bb-named-dragon-shield",
    "name": "Dragon Shield",
    "slot": "shield",
    "visual": "bb-named-dragon-shield",
    "price": 560,
    "armor": 15,
    "defense": 20,
    "rangedDefense": 31,
    "durability": 48,
    "fatigue": 16,
    "collection": "base",
    "sourceKind": "named",
    "sourceCulture": "mercenary",
    "description": "A rare dragon shield with independently rolled Battle Brothers-style modifiers. A large kite shield covered in drawings. Extraordinary craftsmanship went into making this piece.",
    "role": "+20 melee defense, +31 ranged defense; 48 durability at a 16 fatigue cost, with two permanent rolled bonuses.",
    "rarity": "named",
    "sourceNamedShield": true,
    "sourceStats": {
      "armor": 15,
      "defense": 15,
      "rangedDefense": 25,
      "durability": 48,
      "fatigue": 16
    },
    "baseId": "bb-named-dragon-shield",
    "rollVersion": 2,
    "rollModifiers": [
      "ranged-defense",
      "melee-defense"
    ],
    "bonuses": [
      {
        "label": "Ranged defense",
        "value": "+6"
      },
      {
        "label": "Melee defense",
        "value": "+5"
      }
    ]
  },
  {
    "id": "bb-named-full-metal-heater-shield",
    "name": "Full Metal Heater Shield",
    "slot": "shield",
    "visual": "bb-named-full-metal-heater-shield",
    "price": 1050,
    "armor": 20,
    "defense": 26,
    "rangedDefense": 15,
    "durability": 94,
    "fatigue": 16,
    "collection": "base",
    "sourceKind": "named",
    "sourceCulture": "mercenary",
    "description": "A rare full metal heater shield with independently rolled Battle Brothers-style modifiers. A finely crafted heater shield made almost entirely out of metal. Heavy and durable, yet lighter than it looks. The craftsmen who made this must have truly been a master of his trade.",
    "role": "+26 melee defense, +15 ranged defense; 94 durability at a 16 fatigue cost, with two permanent rolled bonuses.",
    "rarity": "named",
    "sourceNamedShield": true,
    "sourceStats": {
      "armor": 20,
      "defense": 20,
      "rangedDefense": 15,
      "durability": 60,
      "fatigue": 16
    },
    "baseId": "bb-named-full-metal-heater-shield",
    "rollVersion": 2,
    "rollModifiers": [
      "melee-defense",
      "durability"
    ],
    "bonuses": [
      {
        "label": "Melee defense",
        "value": "+6"
      },
      {
        "label": "Shield durability",
        "value": "+34"
      }
    ]
  },
  {
    "id": "bb-named-golden-round-shield",
    "name": "Golden Round Shield",
    "slot": "shield",
    "visual": "bb-named-golden-round-shield",
    "price": 1050,
    "armor": 19,
    "defense": 19,
    "rangedDefense": 22,
    "durability": 60,
    "fatigue": 15,
    "collection": "base",
    "sourceKind": "named",
    "sourceCulture": "mercenary",
    "description": "A rare golden round shield with independently rolled Battle Brothers-style modifiers. A full metal round shield of extraordinary quality. This must have been the pride of any warrior boasting it.",
    "role": "+19 melee defense, +22 ranged defense; 60 durability at a 15 fatigue cost, with two permanent rolled bonuses.",
    "rarity": "named",
    "sourceNamedShield": true,
    "sourceStats": {
      "armor": 19,
      "defense": 19,
      "rangedDefense": 17,
      "durability": 60,
      "fatigue": 18
    },
    "baseId": "bb-named-golden-round-shield",
    "rollVersion": 2,
    "rollModifiers": [
      "weight",
      "ranged-defense"
    ],
    "bonuses": [
      {
        "label": "Fatigue cost",
        "value": "-3"
      },
      {
        "label": "Ranged defense",
        "value": "+5"
      }
    ]
  },
  {
    "id": "bb-named-lindwurm-shield",
    "name": "Lindwurm Shield",
    "slot": "shield",
    "visual": "bb-named-lindwurm-shield",
    "price": 910,
    "armor": 15,
    "defense": 18,
    "rangedDefense": 33,
    "durability": 48,
    "fatigue": 16,
    "collection": "lindwurm",
    "sourceKind": "named",
    "sourceCulture": "mercenary",
    "description": "A rare lindwurm shield with independently rolled Battle Brothers-style modifiers. A sturdy wooden frame lays the base for a shimmering heap of rare Lindwurm scales to form a shield impenetrable.",
    "role": "+18 melee defense, +33 ranged defense; 48 durability at a 16 fatigue cost, with two permanent rolled bonuses.",
    "rarity": "named",
    "sourceNamedShield": true,
    "sourceStats": {
      "armor": 15,
      "defense": 15,
      "rangedDefense": 25,
      "durability": 48,
      "fatigue": 16
    },
    "baseId": "bb-named-lindwurm-shield",
    "rollVersion": 2,
    "rollModifiers": [
      "melee-defense",
      "ranged-defense"
    ],
    "bonuses": [
      {
        "label": "Melee defense",
        "value": "+3"
      },
      {
        "label": "Ranged defense",
        "value": "+8"
      }
    ]
  },
  {
    "id": "bb-named-red-white-shield",
    "name": "Red White Shield",
    "slot": "shield",
    "visual": "bb-named-red-white-shield",
    "price": 560,
    "armor": 15,
    "defense": 20,
    "rangedDefense": 25,
    "durability": 48,
    "fatigue": 12,
    "collection": "base",
    "sourceKind": "named",
    "sourceCulture": "mercenary",
    "description": "A rare red white shield with independently rolled Battle Brothers-style modifiers. A large and thick wooden shield of foreign style. It offers great protection despite its peculiar form.",
    "role": "+20 melee defense, +25 ranged defense; 48 durability at a 12 fatigue cost, with two permanent rolled bonuses.",
    "rarity": "named",
    "sourceNamedShield": true,
    "sourceStats": {
      "armor": 15,
      "defense": 15,
      "rangedDefense": 25,
      "durability": 48,
      "fatigue": 16
    },
    "baseId": "bb-named-red-white-shield",
    "rollVersion": 2,
    "rollModifiers": [
      "melee-defense",
      "weight"
    ],
    "bonuses": [
      {
        "label": "Melee defense",
        "value": "+5"
      },
      {
        "label": "Fatigue cost",
        "value": "-4"
      }
    ]
  },
  {
    "id": "bb-named-rider-on-horse-shield",
    "name": "Rider On Horse Shield",
    "slot": "shield",
    "visual": "bb-named-rider-on-horse-shield",
    "price": 700,
    "armor": 20,
    "defense": 20,
    "rangedDefense": 15,
    "durability": 32,
    "fatigue": 12,
    "collection": "base",
    "sourceKind": "named",
    "sourceCulture": "mercenary",
    "description": "A rare rider on horse shield with independently rolled Battle Brothers-style modifiers. A relic heater shield covered in iconographic images. It seem to be old, yet is durable and well to handle.",
    "role": "+20 melee defense, +15 ranged defense; 32 durability at a 12 fatigue cost, with two permanent rolled bonuses.",
    "rarity": "named",
    "sourceNamedShield": true,
    "sourceStats": {
      "armor": 20,
      "defense": 20,
      "rangedDefense": 15,
      "durability": 32,
      "fatigue": 14
    },
    "baseId": "bb-named-rider-on-horse-shield",
    "rollVersion": 2,
    "fatigueOnSkillUse": -3,
    "rollModifiers": [
      "skill-fatigue",
      "weight"
    ],
    "bonuses": [
      {
        "label": "Skill fatigue",
        "value": "-3"
      },
      {
        "label": "Fatigue cost",
        "value": "-2"
      }
    ]
  },
  {
    "id": "bb-named-sipar-shield",
    "name": "Sipar Shield",
    "slot": "shield",
    "visual": "bb-named-sipar-shield",
    "price": 1050,
    "armor": 18,
    "defense": 23,
    "rangedDefense": 18,
    "durability": 60,
    "fatigue": 15,
    "collection": "blazing-deserts",
    "sourceKind": "named",
    "sourceCulture": "south",
    "description": "A rare sipar shield with independently rolled Battle Brothers-style modifiers. A full metal round shield of southern design with elaborate ornaments. Quite heavy, but also durable.",
    "role": "+23 melee defense, +18 ranged defense; 60 durability at a 15 fatigue cost, with two permanent rolled bonuses.",
    "region": "south",
    "rarity": "named",
    "sourceNamedShield": true,
    "sourceStats": {
      "armor": 18,
      "defense": 18,
      "rangedDefense": 18,
      "durability": 60,
      "fatigue": 18
    },
    "baseId": "bb-named-sipar-shield",
    "rollVersion": 2,
    "rollModifiers": [
      "melee-defense",
      "weight"
    ],
    "bonuses": [
      {
        "label": "Melee defense",
        "value": "+5"
      },
      {
        "label": "Fatigue cost",
        "value": "-3"
      }
    ]
  },
  {
    "id": "bb-named-undead-heater-shield",
    "name": "Undead Heater Shield",
    "slot": "shield",
    "visual": "bb-named-undead-heater-shield",
    "price": 500,
    "armor": 20,
    "defense": 28,
    "rangedDefense": 15,
    "durability": 32,
    "fatigue": 10,
    "collection": "base",
    "sourceKind": "named",
    "sourceCulture": "ancient",
    "description": "A rare undead heater shield with independently rolled Battle Brothers-style modifiers. A triangular wooden shield covered with leather and canvas, old but very well balanced.",
    "role": "+28 melee defense, +15 ranged defense; 32 durability at a 10 fatigue cost, with two permanent rolled bonuses.",
    "rarity": "named",
    "sourceNamedShield": true,
    "sourceStats": {
      "armor": 20,
      "defense": 20,
      "rangedDefense": 15,
      "durability": 32,
      "fatigue": 14
    },
    "baseId": "bb-named-undead-heater-shield",
    "rollVersion": 2,
    "rollModifiers": [
      "weight",
      "melee-defense"
    ],
    "bonuses": [
      {
        "label": "Fatigue cost",
        "value": "-4"
      },
      {
        "label": "Melee defense",
        "value": "+8"
      }
    ]
  },
  {
    "id": "bb-named-undead-kite-shield",
    "name": "Undead Kite Shield",
    "slot": "shield",
    "visual": "bb-named-undead-kite-shield",
    "price": 500,
    "armor": 15,
    "defense": 20,
    "rangedDefense": 25,
    "durability": 48,
    "fatigue": 16,
    "collection": "base",
    "sourceKind": "named",
    "sourceCulture": "ancient",
    "description": "A rare undead kite shield with independently rolled Battle Brothers-style modifiers. An elongated wooden shield that offers good protection also to the lower body, despite its apparent age. Somewhat bulky to handle in close combat engagements.",
    "role": "+20 melee defense, +25 ranged defense; 48 durability at a 16 fatigue cost, with two permanent rolled bonuses.",
    "rarity": "named",
    "sourceNamedShield": true,
    "sourceStats": {
      "armor": 15,
      "defense": 15,
      "rangedDefense": 25,
      "durability": 48,
      "fatigue": 16
    },
    "baseId": "bb-named-undead-kite-shield",
    "rollVersion": 2,
    "fatigueOnSkillUse": -2,
    "rollModifiers": [
      "melee-defense",
      "skill-fatigue"
    ],
    "bonuses": [
      {
        "label": "Melee defense",
        "value": "+5"
      },
      {
        "label": "Skill fatigue",
        "value": "-2"
      }
    ]
  },
  {
    "id": "bb-named-wing-shield",
    "name": "Wing Shield",
    "slot": "shield",
    "visual": "bb-named-wing-shield",
    "price": 700,
    "armor": 20,
    "defense": 26,
    "rangedDefense": 15,
    "durability": 32,
    "fatigue": 14,
    "collection": "base",
    "sourceKind": "named",
    "sourceCulture": "mercenary",
    "description": "A rare wing shield with independently rolled Battle Brothers-style modifiers. A reinforced wooden heater shield made from the finest materials and quite obviously crafted by a master shield maker.",
    "role": "+26 melee defense, +15 ranged defense; 32 durability at a 14 fatigue cost, with two permanent rolled bonuses.",
    "rarity": "named",
    "sourceNamedShield": true,
    "sourceStats": {
      "armor": 20,
      "defense": 20,
      "rangedDefense": 15,
      "durability": 32,
      "fatigue": 14
    },
    "baseId": "bb-named-wing-shield",
    "rollVersion": 2,
    "fatigueOnSkillUse": -3,
    "rollModifiers": [
      "melee-defense",
      "skill-fatigue"
    ],
    "bonuses": [
      {
        "label": "Melee defense",
        "value": "+6"
      },
      {
        "label": "Skill fatigue",
        "value": "-3"
      }
    ]
  },
  {
    "id": "bb-metal-round-shield",
    "name": "Sipar Shield",
    "slot": "shield",
    "visual": "bb-metal-round-shield",
    "price": 88,
    "armor": 18,
    "defense": 18,
    "rangedDefense": 18,
    "durability": 60,
    "fatigue": 18,
    "collection": "blazing-deserts",
    "sourceKind": "ordinary",
    "sourceCulture": "south",
    "description": "A full metal round shield of southern design. Quite heavy, but also durable.",
    "role": "+18 melee defense, +18 ranged defense; 60 durability at a 18 fatigue cost.",
    "region": "south"
  },
  {
    "id": "bb-craftable-kraken-shield",
    "name": "Kraken Shield",
    "slot": "shield",
    "visual": "bb-craftable-kraken-shield",
    "price": 420,
    "armor": 24,
    "defense": 24,
    "rangedDefense": 24,
    "durability": 50,
    "fatigue": 15,
    "collection": "beasts-and-exploration",
    "sourceKind": "crafted",
    "sourceCulture": "mercenary",
    "description": "This shield, carved out of a horn plate taken from a giant kraken, is stronger than any common shield. Adapted as equipment; source regeneration and magical effects are not simulated.",
    "role": "+24 melee defense, +24 ranged defense; 50 durability at a 15 fatigue cost."
  },
  {
    "id": "bb-craftable-lindwurm-shield",
    "name": "Lindwurm Shield",
    "slot": "shield",
    "visual": "bb-craftable-lindwurm-shield",
    "price": 280,
    "armor": 17,
    "defense": 17,
    "rangedDefense": 25,
    "durability": 64,
    "fatigue": 14,
    "collection": "lindwurm",
    "sourceKind": "crafted",
    "sourceCulture": "mercenary",
    "description": "This sturdy shield fashioned from the shimmering scales of a Lindwurm makes for protection nigh indestructible. Adapted as equipment; source regeneration and magical effects are not simulated.",
    "role": "+17 melee defense, +25 ranged defense; 64 durability at a 14 fatigue cost."
  },
  {
    "id": "bb-craftable-schrat-shield",
    "name": "Living Tree Shield",
    "slot": "shield",
    "visual": "bb-craftable-schrat-shield",
    "price": 350,
    "armor": 20,
    "defense": 20,
    "rangedDefense": 17,
    "durability": 40,
    "shieldRegeneration": 20,
    "fatigue": 12,
    "collection": "beasts-and-exploration",
    "sourceKind": "crafted",
    "sourceCulture": "mercenary",
    "description": "This shield carved out of the remains of a living tree slowly regrows if it sustains any damage. At a glance, it almost looks as if its grotesque face is still moving. Regenerates 20 durability once per turn while active and unbroken. Surviving shields fully regrow after combat.",
    "role": "+20 melee defense, +17 ranged defense; 40 durability at a 12 fatigue cost."
  },
  {
    "id": "bb-wooden-shield-old",
    "name": "Old Wooden Shield",
    "slot": "shield",
    "visual": "bb-wooden-shield-old",
    "price": 40,
    "armor": 15,
    "defense": 15,
    "rangedDefense": 15,
    "durability": 16,
    "fatigue": 10,
    "collection": "base",
    "sourceKind": "ordinary",
    "sourceCulture": "mercenary",
    "description": "An old round wooden shield.",
    "role": "+15 melee defense, +15 ranged defense; 16 durability at a 10 fatigue cost."
  },
  {
    "id": "bb-worn-heater-shield",
    "name": "Decayed Heater Shield",
    "slot": "shield",
    "visual": "bb-worn-heater-shield",
    "price": 52,
    "armor": 20,
    "defense": 20,
    "rangedDefense": 15,
    "durability": 24,
    "fatigue": 14,
    "collection": "base",
    "sourceKind": "ordinary",
    "sourceCulture": "ancient",
    "description": "A rotten triangular wooden shield covered with leather, canvas and moss.",
    "role": "+20 melee defense, +15 ranged defense; 24 durability at a 14 fatigue cost."
  },
  {
    "id": "bb-worn-kite-shield",
    "name": "Worn Kite Shield",
    "slot": "shield",
    "visual": "bb-worn-kite-shield",
    "price": 52,
    "armor": 15,
    "defense": 15,
    "rangedDefense": 20,
    "durability": 40,
    "fatigue": 16,
    "collection": "base",
    "sourceKind": "ordinary",
    "sourceCulture": "ancient",
    "description": "An elongated wooden shield that offers good protection also to the lower body. Somewhat bulky to handle in close combat engagements.",
    "role": "+15 melee defense, +20 ranged defense; 40 durability at a 16 fatigue cost."
  }
].map(item=>Object.freeze({...item,...(item.sourceStats?{sourceStats:Object.freeze(item.sourceStats),bonuses:Object.freeze(item.bonuses.map(Object.freeze)),rollModifiers:Object.freeze(item.rollModifiers)}:{})})));
