import { DLC_ITEMS } from './dlc-items.js';
import { itemImage } from './portraits.js';
const esc = text => String(text).replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
export const EQUIPMENT_COLLECTIONS = Object.freeze({ all: 'All collections', base: 'Base game', 'warriors-of-the-north': 'Warriors of the North', 'blazing-deserts': 'Blazing Deserts', 'beasts-and-exploration': 'Beasts & Exploration', 'of-flesh-and-faith': 'Of Flesh and Faith', lindwurm: 'Lindwurm', 'supporter-edition': 'Supporter Edition' });
export function equipmentCatalogHTML(collection = 'all') {
  const selected = Object.hasOwn(EQUIPMENT_COLLECTIONS,collection) ? collection : 'all';
  const items = DLC_ITEMS.filter(item=>selected==='all'||item.collection===selected).sort((a,b)=>a.slot.localeCompare(b.slot)||a.name.localeCompare(b.name)||a.id.localeCompare(b.id));
  return `<p>Discover ${DLC_ITEMS.length} armor and helmet designs across the base game and expansions. Northern and southern armories favor their local equipment. Weekly stock rotates; frontier raiders and camps can yield regional gear.</p><label for="equipment-collection">Collection</label><select id="equipment-collection" data-catalog-filter>${Object.entries(EQUIPMENT_COLLECTIONS).map(([id,name])=>`<option value="${id}"${id===selected?' selected':''}>${esc(name)}</option>`).join('')}</select><p>${items.length} designs · Select a piece to inspect protection, weight, and handling.</p><div class="shop-grid">${items.map(item=>`<button class="shop-tile" data-inspect="${item.id}" data-item-source="catalog"><img class="equipment-icon" src="${itemImage(item)}" alt="${esc(item.name)}" loading="lazy"><strong>${esc(item.name)}</strong><small>${item.slot==='armor'?'Body armor':'Helmet'} · ${item.armor} protection · ${item.fatigue} fatigue</small><small>${esc(EQUIPMENT_COLLECTIONS[item.collection])}</small></button>`).join('')}</div>`;
}
