// Eastern and fantasy armor sourced from Fantasy Brothers and Samurai.
export const FANTASY_ITEMS = Object.freeze([
  { id: 'samurai-wushi-armor', name: 'Samurai Armor', slot: 'armor', visual: 'samurai-wushi-armor', price: 650, armor: 180, fatigue: 14, description: 'Lacquered plates and bindings protect the body without the bulk of a full harness.', role: 'Reliable medium armor for a disciplined front-line fighter.' },
  { id: 'samurai-ronin-clothes', name: 'Ronin Clothes', slot: 'armor', visual: 'samurai-ronin-clothes', price: 520, armor: 160, fatigue: 12, description: 'Travel-worn layered clothing with enough reinforcement for a wandering swordsman.', role: 'Mobile protection for a fighter who values stamina over heavy coverage.' },
  { id: 'samurai-ninja-suit', name: 'Ninja Suit', slot: 'armor', visual: 'samurai-ninja-suit', price: 390, armor: 120, fatigue: 9, description: 'Dark close-fitting layers protect the body while leaving room to move.', role: 'Light body armor for a fast scout who avoids prolonged melee and needs spare fatigue.' },
  { id: 'samurai-elite-ninja-suit', name: 'Elite Ninja Suit', slot: 'armor', visual: 'samurai-elite-ninja-suit', price: 560, armor: 165, fatigue: 11, description: 'Reinforced stealth gear with stronger plates over the chest and shoulders.', role: 'A light but durable upgrade for a mobile skirmisher.' },
  { id: 'samurai-monk-soldier-armor', name: 'Monk Soldier Armor', slot: 'armor', visual: 'samurai-monk-soldier-armor', price: 300, armor: 90, fatigue: 6, description: 'Padded robes and modest armor protect a traveling temple guard.', role: 'Very light protection for a reserve fighter or archer who needs a large fatigue reserve.' },
  { id: 'samurai-light-foot-armor', name: 'Lightly Armoured Footman Gear', slot: 'armor', visual: 'samurai-light-foot-armor', price: 320, armor: 90, fatigue: 6, description: 'Simple light armor issued to a foot soldier.', role: 'An inexpensive, low-fatigue choice for a new recruit.' },
  { id: 'samurai-tycoon-armor', name: 'Tycoon Armor', slot: 'armor', visual: 'samurai-tycoon-armor', price: 900, armor: 200, fatigue: 18, description: 'Fine fitted armor worn by a wealthy eastern commander.', role: 'Upper-medium protection with a noticeable stamina cost.' },
  { id: 'samurai-shogun-armor', name: 'Shogun Armor', slot: 'armor', visual: 'samurai-shogun-armor', price: 1050, armor: 200, fatigue: 16, description: 'Ornate lamellar armor built for a lord who still expects to fight.', role: 'Elite medium armor with less weight than full plate.' },

  { id: 'samurai-ninja-mask', name: 'Ninja Mask', slot: 'helmet', visual: 'samurai-ninja-mask', price: 140, armor: 80, fatigue: 4, description: 'A wrapped mask and cap soften glancing blows to the head.', role: 'Light head protection for mobile skirmishers who prefer spare fatigue over heavy armor.' },
  { id: 'samurai-elite-ninja-mask', name: 'Elite Ninja Mask', slot: 'helmet', visual: 'samurai-elite-ninja-mask', price: 270, armor: 150, fatigue: 6, description: 'A reinforced mask with a rigid crown over the skull.', role: 'Medium head protection for a mobile fighter who wants more durability without a heavy helm.' },
  { id: 'samurai-monk-mask', name: 'Monk Soldier Mask', slot: 'helmet', visual: 'samurai-monk-mask', price: 95, armor: 40, fatigue: 1, description: 'A light cloth face covering worn by temple soldiers.', role: 'Minimal protection with almost no fatigue burden.' },
  { id: 'samurai-bamboo-hat', name: 'Bamboo Hat', slot: 'helmet', visual: 'samurai-bamboo-hat', price: 125, armor: 60, fatigue: 2, description: 'A broad woven hat that turns rain and glancing strikes.', role: 'Light headgear for archers and travelers who need stamina more than front-rank protection.' },
  { id: 'samurai-helmet', name: 'Samurai Helmet', slot: 'helmet', visual: 'samurai-helmet', price: 310, armor: 160, fatigue: 6, description: 'A crested iron helmet protects the head while keeping the face visible.', role: 'Balanced medium protection for a front-line fighter.' },
  { id: 'samurai-tycoon-helmet', name: 'Tycoon Helmet', slot: 'helmet', visual: 'samurai-tycoon-helmet', price: 420, armor: 180, fatigue: 6, description: 'A decorated helmet with a rigid crown and cheek guards.', role: 'Strong head protection at a moderate fatigue cost.' },
  { id: 'samurai-shogun-helmet', name: 'Shogun Helmet', slot: 'helmet', visual: 'samurai-shogun-helmet', price: 480, armor: 180, fatigue: 6, description: 'An imposing helmet reserved for a high-ranking commander.', role: 'Strong head protection for a shield bearer who expects repeated hits in the front rank.' },
  { id: 'samurai-ronin-hat', name: 'Ronin Hat', slot: 'helmet', visual: 'samurai-ronin-hat', price: 125, armor: 60, fatigue: 2, description: 'A travel hat with a stiffened crown for a wandering swordsman.', role: 'Light protection that suits a fast, lightly armored fighter.' },

  { id: 'fantasy-wokou-armor', name: 'Wokou Light Armor', slot: 'armor', visual: 'fantasy-wokou-armor', price: 360, armor: 100, fatigue: 9, description: 'Light eastern armor made for a raider who must stay quick.', role: 'Low-fatigue protection for a mobile fighter who avoids a long stand against armored enemies.' },
  { id: 'fantasy-samurai-armor', name: 'Fantasy Samurai Armor', slot: 'armor', visual: 'fantasy-samurai-armor', price: 1050, armor: 300, fatigue: 36, description: 'Heavy lamellar plates cover the body from shoulder to thigh.', role: 'Elite body protection with a substantial stamina cost.' },
  { id: 'fantasy-kasaya', name: 'Kasaya', slot: 'armor', visual: 'fantasy-kasaya', price: 110, armor: 20, fatigue: 0, description: 'A simple robe worn by eastern meditators.', role: 'Nearly weightless clothing with little protection.' },
  { id: 'fantasy-grand-steel-armor', name: 'Grand Steel Armor', slot: 'armor', visual: 'fantasy-grand-steel-armor', price: 1200, armor: 320, fatigue: 42, description: 'A masterpiece of forged steel, heavy enough to turn aside hard blows.', role: 'Maximum body protection, balanced by the heaviest fatigue load.' },

  { id: 'fantasy-knight-helm', name: 'Knight Helm', slot: 'helmet', visual: 'fantasy-knight-helm', price: 780, armor: 300, fatigue: 20, description: 'A fully enclosing great helm shields the head behind thick steel.', role: 'Maximum head protection with a severe fatigue cost.' },
  { id: 'fantasy-red-dragon-helm', name: 'Red Dragon Helmet', slot: 'helmet', visual: 'fantasy-red-dragon-helm', price: 900, armor: 300, fatigue: 15, description: 'A striking dragon-crested helm backed by a heavy steel shell.', role: 'Maximum head protection with a somewhat lower fatigue load.' },
  { id: 'fantasy-eastern-helm', name: 'Eastern Helm', slot: 'helmet', visual: 'fantasy-eastern-helm', price: 650, armor: 250, fatigue: 17, description: 'A high-domed eastern helmet protects the skull and temples.', role: 'Heavy head protection for a seasoned front-line fighter.' },
  { id: 'fantasy-kasa', name: 'Kasa', slot: 'helmet', visual: 'fantasy-kasa', price: 180, armor: 105, fatigue: 5, description: 'A stiffened wide-brim hat offers modest protection from rain and arrows.', role: 'Light head protection that preserves mobility.' },
]);
