// Matching frontier equipment; reuses the existing credited Legends artwork.
export const FRONTIER_ITEMS = Object.freeze([
  { id: 'frontier-scout-armor', name: 'Frontier Scout Armor', slot: 'armor', visual: 'wolf-gambeson', price: 260, armor: 100, fatigue: 10, description: 'Issued to frontier scout companies guarding the eastern trade roads.', role: 'Moderate protection for a mobile fighter who needs endurance for ranged attacks.' },
  { id: 'frontier-scout-helmet', name: 'Frontier Scout Helm', slot: 'helmet', visual: 'high-kettle-helm', price: 230, armor: 105, fatigue: 8, description: 'Issued to frontier scout companies guarding the eastern trade roads.', role: 'Moderate protection for a mobile fighter who needs endurance for ranged attacks.' },
  { id: 'frontier-warden-armor', name: 'March Warden Armor', slot: 'armor', visual: 'reinforced-lamellar', price: 610, armor: 240, fatigue: 29, description: 'Issued to march warden companies guarding the eastern trade roads.', role: 'Heavy protection for a dependable front rank holding the eastern trade roads.' },
  { id: 'frontier-warden-helmet', name: 'March Warden Helm', slot: 'helmet', visual: 'flat-top-helm', price: 355, armor: 190, fatigue: 17, description: 'Issued to march warden companies guarding the eastern trade roads.', role: 'Heavy protection for a dependable front rank holding the eastern trade roads.' },
  { id: 'frontier-sentinel-armor', name: 'Eastern Sentinel Armor', slot: 'armor', visual: 'plate-cuirass', price: 690, armor: 280, fatigue: 34, description: 'Issued to eastern sentinel companies guarding the eastern trade roads.', role: 'Plate protection for a veteran with ample endurance.' },
  { id: 'frontier-sentinel-helmet', name: 'Eastern Sentinel Helm', slot: 'helmet', visual: 'full-helm', price: 465, armor: 240, fatigue: 23, description: 'Issued to eastern sentinel companies guarding the eastern trade roads.', role: 'Plate protection for a veteran with ample endurance.' },
]);
